/* Arquivo carregado depois de engine.js, data.js, core.js e slides.js (ver build.py). */
/* ---------- forças de mercado ---------- */
(function(){const F=[["spark","IA: uso amplo, retorno raro","Quase todas as grandes empresas usam IA, mas poucas saem do piloto e provam resultado no caixa.","56%","dos CEOs ainda sem retorno financeiro com IA","PwC, 29ª CEO Survey · jan/2026","Vender valor medido e governança de IA, não estratégia genérica."],
   ["doc","Reforma Tributária e fim do SAP ECC","Dois prazos com data marcada obrigam a mexer em ERP, fiscal e dados ao mesmo tempo.","01/01/27","CBS plena; manutenção padrão do SAP ECC termina em 2027","LC 214/2025 · Baguete","Produtos com prazo e preço fixos: prontidão e resgate de projetos."],
   ["deal","Deals liderados por private equity","Menos transações, tickets maiores e fundos em metade dos deals; tecnologia é o setor mais negociado.","50%","das transações de 2025 com fundos de PE ou VC","KPMG, Fusões e Aquisições 2025 · mar/2026","Diligência rápida, Dia 1 garantido e sinergias que viram EBITDA."],
   ["coin","Custo de tecnologia sob escrutínio","O orçamento de TI desacelera, licenças sobem e contratos em dólar pesam no caixa.","8–15×","alta de licenças VMware após a compra pela Broadcom","Baguete · ABES/IDC (TI +5,3% em 2026)","Otimização de gastos com economia certificada e radar contínuo."],
   ["shield","Risco operacional e regulação","Ataques à cadeia do Pix e novas regras do Banco Central elevam a exigência sobre terceiros de TI.","R$ 800 mi","desviados no ataque à C&M Software (jul/2025)","Finsiders · Res. CMN 5.274/2025","Resiliência, recuperação e avaliação de risco de terceiros."],
   ["people","Talento e liderança escassos","Metade das empresas não tem o talento necessário para IA; transações e reestruturações pedem liderança imediata.","53%","das empresas sem o talento necessário para IA","KPMG Global Tech Report 2026","Liderança interina e modelo operacional para a era dos agentes."]];
  F.forEach(([ic,t,x,v,vl,src,imp],i)=>{const d=H("div",{class:"f2","data-a":"mask",style:`--d:${4+i*1.5}`},$("forces"));d.innerHTML=`<div class="hd"><div class="ic">${ico(ic)}</div><h4>${t}</h4></div><div class="th">${x}</div><div class="v">${v}<small>${vl}</small></div><div class="src">Fonte: ${src}</div><div class="imp"><b>Para o DTS</b>${imp}</div>`})})();

