/* =====================================================================
   DADOS · novo portfólio DTS (24 produtos) + portfólio atual (29 serviços)
   Convenção: [E] evidência com fonte · [H] hipótese/proposta a validar
   ===================================================================== */
const E=t=>`<span class="ev">${t?"E · "+t:"Evidência"}</span>`;
const Hy=t=>`<span class="hy">${t||"Hipótese"}</span>`;

const PILLARS=[
  {n:1,name:"IT Advisory",official:"IT Advisory",to:"IT Advisory · Strategy, Leadership & Value",short:"Estratégia, liderança e valor de tecnologia",
   def:"Apoiamos líderes nas decisões de tecnologia e IA que movem o resultado: diagnóstico, estratégia investível, liderança interina, modelo operacional e custo.",
   def_as:"Apoiamos líderes na tomada de decisões estratégicas por meio de soluções de TI que integram diagnóstico, transformação e governança, acelerando resultados, mitigando riscos e gerando valor.",
   when:"Empresas que enfrentam desafios na transformação da área de TI, custos elevados com tecnologia ou necessidade de redefinir sua direção tecnológica.",
   was:10,now:7,nnew:1},
  {n:2,name:"Technology Transformation",official:"Technology Transformation",to:"Technology Transformation",short:"Execução de transformações complexas",
   def:"Garantimos que programas críticos de tecnologia entreguem: escolha de fornecedores, ERP e Reforma Tributária, governança preditiva, resgate de projetos e adoção.",
   def_as:"Apoiamos na execução de projetos estratégicos complexos, garantindo implementações bem-sucedidas e alinhamento entre tecnologia e objetivos de negócio.",
   when:"Empresas que executam projetos estratégicos e transformacionais de TI, com alto risco e impacto para o negócio.",
   was:7,now:6,nnew:1},
  {n:3,name:"Tech M&A",official:"Technology M&A Advisory & Transformation",to:"Tech M&A & Value Creation",short:"Tecnologia em todo o ciclo do deal",
   def:"Protegemos e criamos valor de tecnologia do signing à saída: due diligence com IA, Dia 1, integração e separação, sinergias e monitoramento de portfólio.",
   def_as:"Oferecemos suporte estratégico e especializado em todo o ciclo de M&A, com foco em tecnologia, garantindo excelência na execução e aproveitamento de sinergias para maximizar o valor da transação.",
   when:"Fundos de investimento e empresas em processos de aquisição ou venda, da definição da estratégia à execução da transição.",
   was:8,now:5,nnew:1},
  {n:4,name:"Modernization",official:"Technological Modernization & Digital Evolution",to:"Modernization & AI-Ready Technology",short:"Arquitetura, legado, infraestrutura e resiliência",
   def:"Modernizamos arquitetura, aplicações e infraestrutura para a era da IA, com custo sob controle, migrações garantidas e operação resiliente.",
   def_as:"Entregamos soluções em arquitetura de TI e governança, modernizando sistemas e infraestruturas para garantir alinhamento estratégico e sustentabilidade a longo prazo.",
   when:"Empresas que precisam avaliar e modernizar suas arquiteturas e infraestruturas de TI, otimizando custos e aumentando a eficiência operacional.",
   was:4,now:6,nnew:1}
];

/* ---------- PORTFÓLIO ATUAL (29) · avaliação qualitativa DTS [H] ----------
   x = atratividade de mercado Brasil 2026–27 (1–5) · y = direito de vencer A&M (1–5)
   d = decisão: keep | ai | merge | cut · to = produto de destino               */
const OLD=[
 {id:"a1",p:1,n:"Tech Maturity & Value Assessment",x:3.6,y:3.2,d:"ai",to:"1.1",w:"Demanda alta, mas diagnósticos de maturidade se comoditizam com IA: precisa virar valor em R$ e prontidão para IA."},
 {id:"a2",p:1,n:"C-Level Tech Enablement",x:2.6,y:2.4,d:"merge",to:"1.3",w:"Pouco tangível isolado; vira módulo 'Board & C-Level AI Fluency' dentro da liderança interina."},
 {id:"a3",p:1,n:"Embedded Tech Leadership",x:3.0,y:3.8,d:"merge",to:"1.3",w:"Sobrepõe Interim CIO/CTO: mesmo comprador, mesma bancada de executivos."},
 {id:"a4",p:1,n:"Interim CIO / CTO Leadership",x:3.6,y:4.7,d:"keep",to:"1.3",w:"DNA A&M (interim management). Não foi encontrada oferta equivalente nas Big Four."},
 {id:"a5",p:1,n:"Digital Strategy & Roadmapping",x:3.4,y:2.6,d:"ai",to:"1.2",w:"Mercado saturado (estratégia, Big Four, integradores). Reposicionar para roadmap investível de tecnologia e IA."},
 {id:"a6",p:1,n:"Operating Model Design & Tech Org Restructuring",x:3.8,y:4.0,d:"ai",to:"1.4",w:"Reestruturação é DNA A&M; precisa incorporar força de trabalho humano + agentes."},
 {id:"a7",p:1,n:"IT Resilience & Business Continuity Planning",x:3.7,y:2.8,d:"ai",to:"4.5",w:"Demanda sobe (CMN 5.274, ataques C&M/Sinqia). Move para Modernização: resiliência é arquitetura."},
 {id:"a8",p:1,n:"Tech Spend Optimization",x:4.6,y:4.6,d:"ai",to:"1.5",w:"Câmbio, VMware e TI crescendo só 5,3% em 2026: carro-chefe. Ganha radar contínuo com IA."},
 {id:"a9",p:1,n:"Strategic Tech Tax / Accounting Planning",x:2.8,y:2.6,d:"merge",to:"1.6",w:"Nicho; mais forte combinado a incentivos e em parceria com A&M Tax."},
 {id:"a10",p:1,n:"Innovation Tax Incentives Advisory",x:3.2,y:2.4,d:"merge",to:"1.6",w:"Lei do Bem: 4,2 mil empresas, corte de 10% pela LC 224. Diferencia com leitura técnica por IA."},
 {id:"b1",p:2,n:"IT Sourcing (Software & Vendor) Selection",x:3.4,y:3.2,d:"ai",to:"2.1",w:"IA comprime RFP e avaliação; diferencial é independência e negociação."},
 {id:"b2",p:2,n:"ERP Readiness & Gap Analysis",x:4.6,y:3.4,d:"ai",to:"2.2",w:"Janela única: Reforma Tributária (CBS 2027) + fim da manutenção padrão do SAP ECC em 2027."},
 {id:"b3",p:2,n:"TMO",x:3.6,y:3.6,d:"ai",to:"2.3",w:"PMO sem accountability se comoditiza; TMO preditivo com IA e foco em valor."},
 {id:"b4",p:2,n:"Gestão de Mudanças Tech",x:3.4,y:2.6,d:"ai",to:"2.5",w:"Reposicionar para adoção de IA (Copilots, agentes), medida por dados de uso."},
 {id:"b5",p:2,n:"Modelo de Implantação e Governança",x:2.4,y:2.8,d:"merge",to:"2.3",w:"Mesmo comprador e método do TMO: fundir."},
 {id:"b6",p:2,n:"Project Remediation",x:4.0,y:4.6,d:"keep",to:"2.4",w:"Turnaround de projetos é DNA A&M; Reforma e ERPs atrasados aumentam a demanda."},
 {id:"b7",p:2,n:"IT Business Partner",x:2.0,y:2.2,d:"cut",to:"1.3",w:"Alocação de perfil, baixa diferenciação e margem; absorvido pela liderança embarcada."},
 {id:"c1",p:3,n:"IT M&A Playbook",x:2.2,y:3.0,d:"cut",to:"3.5",w:"Pouco vendável isolado; vira ativo interno que alimenta todos os produtos de M&A."},
 {id:"c2",p:3,n:"IT Due Diligence (Buy Side)",x:4.4,y:4.0,d:"ai",to:"3.1",w:"PE em 50% dos deals; concorrentes já usam IA (PwC Harvey/ToltIQ). Acelerar é obrigatório."},
 {id:"c3",p:3,n:"IT Integration & Separation Planning",x:3.8,y:3.8,d:"merge",to:"3.2",w:"Mesmo método do desenho de separação: um blueprint para as duas direções."},
 {id:"c4",p:3,n:"IT Integration Management Office",x:3.6,y:4.0,d:"merge",to:"3.3",w:"IMO e SMO são a mesma disciplina em sentidos opostos."},
 {id:"c5",p:3,n:"IT Due Diligence (Sell Side)",x:3.4,y:3.4,d:"merge",to:"3.1",w:"Vira a edição sell-side / vendor readiness do mesmo produto de DD."},
 {id:"c6",p:3,n:"IT Separation Strategy & Design",x:3.6,y:4.2,d:"merge",to:"3.2",w:"Carve-outs são força A&M; unificado ao blueprint de integração."},
 {id:"c7",p:3,n:"IT Separation Management Office",x:3.4,y:4.2,d:"merge",to:"3.3",w:"Unificado ao IMO: governança única para Dia 1 e saída de TSA."},
 {id:"c8",p:3,n:"IT Synergies & Value Creation",x:4.0,y:4.0,d:"keep",to:"3.4",w:"Alinhado à prática de PE da A&M; manter como plano de 100 dias."},
 {id:"d1",p:4,n:"Strategy Architecture",x:3.4,y:2.6,d:"ai",to:"4.1",w:"Nome pouco claro ao mercado; reposicionar para arquitetura pronta para IA e dívida técnica em R$."},
 {id:"d2",p:4,n:"Strategy Application",x:3.2,y:2.8,d:"ai",to:"4.2",w:"Renomear para racionalização de portfólio de aplicações, ligada a custo."},
 {id:"d3",p:4,n:"Infrastructure Management",x:3.8,y:2.4,d:"ai",to:"4.3",w:"Soa como serviço gerenciado (onde integradores dominam); virar advisory de decisão e custo: nuvem, VMware, GPU."},
 {id:"d4",p:4,n:"Complex Migrations Support",x:3.6,y:3.4,d:"keep",to:"4.4",w:"Reposicionar como assurance independente do integrador."}
];
const NEWPOS=[{c:"1.7",x:4.4,y:3.6},{c:"2.6",x:3.9,y:3.1},{c:"3.5",x:3.8,y:4.3},{c:"4.6",x:4.2,y:3.3}];

/* ---------- NOVO PORTFÓLIO (24) ---------- */
const PRODUCTS=[
/* ======================= PILAR 1 ======================= */
{id:"tech-ai-value-diagnostic",code:"1.1",pillar:1,st:"ai",name:"Tech & AI Value Diagnostic",from:"Tech Maturity & Value Assessment",
 tagline:"Em 3 semanas: onde a TI gera, perde e pode capturar valor",
 pitch:"Diagnóstico rápido e quantificado de maturidade de tecnologia e de prontidão para IA que termina em <b>valor em jogo (R$)</b> e em uma lista priorizada de decisões, não em um relatório de maturidade.",
 meta:["Duração: 3 semanas","Comprador: CEO · CFO · CIO · conselho · PE","Preço fixo por porte","Porta de entrada para 1.2 · 1.4 · 1.5"],
 kpis:[["3 sem.","do kick-off ao valor em jogo"],["7 lentes","estratégia · gasto · arquitetura · dados · IA · pessoas · risco"],["56%","dos CEOs ainda sem retorno financeiro com IA [E · PwC 2026]"]],
 who:["CEO/CFO que questionam o retorno da tecnologia","CIO recém-chegado (primeiros 100 dias)","Fundos de PE em empresas recém-adquiridas","Conselhos preparando a agenda de IA"],
 pain:["TI cara e pouco comparável com o mercado","IA em pilotos sem ROI mensurável","Diagnósticos longos que viram slides, não decisões"],
 deliv:["Scorecard de maturidade (7 lentes) com benchmark","Mapa de valor em jogo (R$) por alavanca","Índice de prontidão para IA","Top-10 decisões com dono e prazo","Roadmap de 90 dias"],
 skills:["Finanças de TI (TBM)","Arquitetura","Analytics","IA aplicada","Facilitação executiva"],
 steps:[["S1","Coleta inteligente","Data request padrão; agente de IA ingere contratos, orçamento, inventários e tickets"],["S1–2","Entrevistas e pulso","10–15 entrevistas + survey digital com 50–200 respondentes"],["S2","Benchmark","Comparação com base DTS e referências de mercado; scoring das 7 lentes"],["S3","Valor em jogo","Alavancas quantificadas em R$ e priorizadas por valor × esforço"],["S3","Decisões","Workshop executivo e roadmap de 90 dias"]],
 tools:"Ambiente de diagnóstico DTS (formulário + Power BI), LLM corporativo em ambiente seguro (conforme política do cliente), base de benchmark DTS, quadro colaborativo (Miro/Mural).",
 data:"Orçamento e razão contábil de TI, contratos e faturas, inventário de aplicações e infraestrutura, organograma e headcount, tickets de ITSM, portfólio de projetos, respostas do survey.",
 ai:["Lê e classifica centenas de documentos (contratos, faturas, inventários) em horas","Gera o primeiro rascunho do scorecard com <b>evidência citada</b>; o time revisa e assina","Sintetiza entrevistas e survey em temas e citações","Simula o valor em jogo por alavanca com premissas explícitas"],
 prodz:["Escopo fixo de 3 semanas e preço por faixa de receita","Kit replicável: data request, roteiros, questionário, scoring e relatório","Cada projeto alimenta o benchmark DTS (ativo de dados proprietário)","Crédito do diagnóstico no projeto seguinte (1.2, 1.4, 1.5)"],
 bench:"<b>Mercado:</b> KPMG ‘CIO Advisory’ (TBM/Apptio) e EY ‘Technology Strategy & Transformation · Office of the CIO’ fazem diagnósticos de maturidade "+E("sites/vagas 2025–26")+". <b>Diferencial A&M:</b> velocidade, valor em R$ e foco em decisão "+Hy()+".",
 ev:"Dados: PwC 29ª CEO Survey (jan/2026); KPMG e EY via páginas de serviço e vagas. Duração, lentes e preço são proposta DTS."},
{id:"tech-ai-strategy-roadmap",code:"1.2",pillar:1,st:"ai",name:"Tech & AI Strategy Roadmap",from:"Digital Strategy & Roadmapping",
 tagline:"Estratégia de tecnologia e IA investível: casos de uso, sequência e business case",
 pitch:"Converte a ambição do negócio em um <b>roadmap investível de tecnologia e IA</b>: iniciativas com business case, sequência, capacidade e governança, prontas para aprovação no conselho.",
 meta:["Duração: 6–8 semanas","Comprador: CEO · CIO · conselho","Preço fixo por fase","Gatilho de 1.7 e 2.3"],
 kpis:[["6–8 sem.","da ambição ao plano aprovado"],["~25%","das empresas escalam ≥40% dos pilotos de IA [E · Deloitte 2026]"],["3 horizontes","ganhos rápidos · escala · transformação"]],
 who:["CEOs e conselhos definindo a agenda de IA","CIOs construindo o plano de 3–5 anos","Empresas pós-transação com novo controlador"],
 pain:["Estratégias digitais genéricas, sem dono nem orçamento","Dezenas de pilotos de IA sem priorização","Roadmaps que ignoram capacidade, dados e financiamento"],
 deliv:["Tese de valor de tecnologia e IA","Portfólio priorizado de casos de uso (valor × viabilidade × risco)","Arquitetura-alvo em alto nível","Roadmap em 3 horizontes com investimento","Business case e modelo de governança (board pack)"],
 skills:["Estratégia","Design thinking","Arquitetura","Business case","IA aplicada"],
 steps:[["S1–2","Ambição","Entrevistas C-level, tese de valor e cadeia de valor"],["S2–4","Oportunidades","Fábrica de casos de uso com IA: ideação assistida + benchmark setorial"],["S4–5","Priorização","Valor × viabilidade × risco; dependências de dados"],["S5–7","Roadmap","Ondas, capacidade, investimento e business case"],["S8","Aprovação","Board pack e governança de execução"]],
 tools:"Biblioteca DTS de casos de uso por setor, modelo padrão de business case e scoring, LLM para pesquisa e ideação, Power BI/Excel e quadro colaborativo para o roadmap.",
 data:"Plano estratégico, P&L por unidade, mapa de processos, inventário de dados e sistemas, resultado do 1.1 (quando houver).",
 ai:["Pesquisa setorial e de concorrentes em horas","Gera e enriquece casos de uso a partir de processos e dores mapeadas","Estima valor com premissas rastreáveis e análise de sensibilidade","Redige o board pack para revisão do time"],
 prodz:["Biblioteca de casos de uso por indústria, reaproveitada a cada projeto","Modelo padrão de business case e scoring","Fases com preço fixo: Ambição → Portfólio → Roadmap","Desdobra em 1.7 (governar o portfólio) e 2.3 (executar)"],
 bench:"<b>Mercado:</b> saturado; McKinsey/QuantumBlack, BCG X, Deloitte e EY oferecem estratégia de IA "+E()+". <b>Diferencial A&M:</b> roadmap ‘investível’, ligado a caixa e execução, em vez de visão genérica "+Hy()+".",
 ev:"Dado de escala de pilotos: Deloitte State of AI 2026 (Brasil). Posicionamento: proposta DTS."},
{id:"interim-embedded-tech-leadership",code:"1.3",pillar:1,st:"keep",sig:true,name:"Interim & Embedded Tech Leadership",from:"Interim CIO / CTO Leadership + Embedded Tech Leadership + C-Level Tech Enablement (+ IT Business Partner)",
 tagline:"Liderança de tecnologia que assume o cargo: CIO, CTO, CDO e CAIO interinos",
 pitch:"A A&M coloca <b>executivos seniores de tecnologia no comando</b>, interinos ou embarcados ao lado do C-level, para estabilizar, decidir e entregar durante transição, crise, transação ou transformação.",
 meta:["Duração: 3–12 meses","Comprador: CEO · conselho · sócio de PE","Fee mensal + bônus por marcos","Inclui módulo Board & C-Level AI Fluency"],
 kpis:[["< 2 sem.","para alocar o executivo (meta de serviço)"],["100 dias","plano de comando com marcos"],["4 papéis","CIO · CTO · CDO · Chief AI Officer"]],
 who:["Empresas sem CIO (saída abrupta, M&A, turnaround)","Fundos de PE logo após a aquisição","Empresas que precisam de um Chief AI Officer antes de contratar","Conselhos que precisam de fluência em tecnologia e IA"],
 pain:["Vacância ou fragilidade da liderança de TI em momento crítico","Transformação sem dono","Conselho sem repertório para decidir sobre IA"],
 deliv:["Executivo alocado (interino ou embarcado)","Plano de 100 dias","Estabilização e decisões críticas","Sucessão: recrutamento e passagem de bastão","Programa Board & C-Level AI Fluency"],
 skills:["Liderança executiva","Gestão de crise","Governança","Finanças de TI","Comunicação com conselho"],
 steps:[["S0","Match","Perfil e seleção na rede A&M (global + Brasil)"],["D1–30","Estabilizar","Diagnóstico rápido (1.1 light) e decisões imediatas"],["D30–100","Comandar","Plano de 100 dias: time, orçamento, fornecedores"],["M4+","Transformar","Execução do roadmap e reporte ao conselho"],["Fim","Passar o bastão","Sucessor contratado, onboarding e saída"]],
 tools:"Playbook A&M de 100 dias, copiloto do executivo interino (IA sobre a base de conhecimento DTS e documentos do cliente), dashboards de gestão, rede global de executivos A&M.",
 data:"Orçamento, portfólio de projetos, contratos, organograma, indicadores de serviço e atas de comitês.",
 ai:["Copiloto do interino: briefing da 1ª semana gerado a partir dos documentos da empresa","Monitora riscos e compromissos (contratos, prazos, renovações)","Trilhas personalizadas de AI Fluency por papel no conselho","Playbooks consultáveis em linguagem natural"],
 prodz:["Bancada de executivos pré-qualificados com SLA de alocação","Playbook de 100 dias padronizado + kit de ferramentas","Fee mensal por senioridade + variável por marcos","Porta de entrada do portfólio: o interino enxerga as próximas necessidades"],
 bench:"<b>Mercado:</b> nas Big Four, não foi encontrada oferta de CIO interino (resultado da pesquisa DTS, 2026); a restrição de independência em clientes de auditoria é uma explicação provável "+Hy()+". O par mais próximo, AlixPartners, oferece CIO interino para PE "+E("AlixPartners (fonte fraca)")+". <b>Diferencial A&M:</b> espaço livre no Brasil e DNA histórico da A&M em interim management.",
 ev:"Ausência de oferta equivalente nas Big Four: resultado da pesquisa (não encontrado ≠ inexistente). SLA e preço: proposta DTS."},
{id:"ai-era-tech-operating-model",code:"1.4",pillar:1,st:"ai",name:"AI-Era Tech Operating Model",from:"Operating Model Design & Tech Org Restructuring",
 tagline:"Organização de TI para a era dos agentes: produto, plataforma e força de trabalho humano + IA",
 pitch:"Redesenha <b>estrutura, papéis, processos e custos</b> da tecnologia para operar com produtos digitais, plataformas e agentes de IA, com dimensionamento, business case e plano de transição.",
 meta:["Duração: 8–10 semanas","Comprador: CEO · CIO · CHRO","Preço fixo + opção de implementação","Combina com 2.6 e 1.5"],
 kpis:[["8–10 sem.","do diagnóstico ao modelo aprovado"],["53%","das empresas não têm o talento necessário para IA [E · KPMG Global Tech]"],["1 mapa","papéis humano × agente por processo de TI"]],
 who:["CIOs pressionados por eficiência","Empresas em reestruturação ou turnaround","Pós-fusão com duas áreas de TI","Empresas migrando de projeto para produto"],
 pain:["Estruturas por projeto ou torre que não escalam IA","Sobreposição de papéis e de terceiros","Falta de talento e de trilhas de requalificação"],
 deliv:["Modelo operacional-alvo (produto/plataforma)","Organograma, spans & layers e dimensionamento","Mapa da força de trabalho humano + agentes","Modelo de sourcing (interno × parceiros)","Business case e plano de transição"],
 skills:["Organization design","Gestão de mudança","Finanças de TI","Workforce analytics","IA aplicada"],
 steps:[["S1–2","Linha de base","Headcount, terceiros, custos, demanda e atividades"],["S3–4","Desenho","Princípios, modelo produto/plataforma e governança"],["S5–6","Agentes","Atividade × potencial de IA; papéis novos (AI Ops, agent owner)"],["S7–8","Dimensionar","Spans & layers, custo-alvo, sourcing"],["S9–10","Transição","Ondas, comunicação e riscos"]],
 tools:"Modelo de dimensionamento DTS, taxonomia de atividades de TI, Power BI para workforce analytics, LLM para analisar descrições de cargo e tickets.",
 data:"Folha e headcount, contratos de terceiros, tickets e demanda, catálogo de serviços, descrições de cargo.",
 ai:["Classifica atividades e cargos por potencial de automação e de agentes","Analisa tickets e demanda para dimensionar capacidade","Simula cenários de força de trabalho humano + IA","Redige descrições de papéis novos e trilhas de requalificação"],
 prodz:["Taxonomia de atividades de TI + biblioteca de papéis da era agêntica","Simulador de dimensionamento reaproveitável","Fases com preço fixo; implementação via 1.3 ou 2.3","Benchmark de spans & layers acumulado"],
 bench:"<b>Mercado:</b> EY (IT Operating Model) e Deloitte (Technology Strategy & Transformation) cobrem op model "+E()+". <b>Diferencial A&M:</b> reestruturação com execução e captura de custo "+Hy()+".",
 ev:"Dado de talento: KPMG Global Tech Report 2025/26. Demais parâmetros: proposta DTS."},
{id:"tech-spend-optimization",code:"1.5",pillar:1,st:"ai",sig:true,name:"Tech Spend Optimization & Spend Radar",from:"Tech Spend Optimization",
 tagline:"Cortar o que não gera valor e manter o radar ligado com IA",
 pitch:"Programa de redução de gastos de tecnologia (contratos, licenças, nuvem, terceiros e projetos) com <b>economia certificada</b>, seguido de um <b>Spend Radar</b> contínuo com IA que impede o custo de voltar.",
 meta:["Duração: 10–12 semanas + assinatura","Comprador: CFO · CIO · sócio de PE","Fixo reduzido + % da economia","Radar: assinatura mensal"],
 kpis:[["20–30%","otimização típica de nuvem com FinOps maduro [E · IT Forum]"],["8–15×","alta de licenças VMware pós-Broadcom [E · Baguete]"],["29%","do gasto em nuvem é desperdiçado [E · Flexera 2026]"]],
 who:["CFOs e CIOs sob pressão de orçamento 2027","Empresas com contratos de tecnologia em dólar","Fundos de PE (alavanca de EBITDA)","Empresas em turnaround"],
 pain:["Gasto de TI fragmentado e opaco","Até 40% dos insumos de TI importados; renovações automáticas em dólar "+"(TI Inside 2025)","Shelfware de SaaS, nuvem sem FinOps, virtualização mais cara"],
 deliv:["Cubo de gastos de TI (taxonomia TBM)","Pipeline de economias validado com Finanças","Renegociações e consolidações executadas","Plano de FinOps e de licenças","Spend Radar: painel contínuo com alertas"],
 skills:["Negociação","TBM / FinOps","Análise de contratos","Analytics","Gestão de fornecedores"],
 steps:[["S1–2","Cubo de gastos","Razão, faturas e contratos na taxonomia TBM"],["S3–4","Oportunidades","Benchmark, licenças, nuvem, terceiros, projetos"],["S5–10","Captura","Renegociar, consolidar, cancelar, FinOps"],["S11–12","Certificação","Economia validada com Finanças"],["Contínuo","Spend Radar","Renovações, anomalias e preços"]],
 tools:"Spend Radar DTS (pipeline de dados + Power BI), APIs de custo de AWS/Azure/GCP, ferramentas de mercado quando existirem no cliente (Apptio, Flexera, ServiceNow SAM), LLM para contratos.",
 data:"Razão contábil, notas fiscais e faturas, contratos e aditivos, billing de nuvem, inventário de licenças, câmbio (PTAX).",
 ai:["Lê contratos: datas de renovação, reajuste, saída e cláusula cambial","Classifica faturas na taxonomia TBM automaticamente","Detecta anomalias, duplicidades e licenças ociosas","Monta o dossiê de negociação com benchmarks e alternativas"],
 prodz:["Risco compartilhado: fixo reduzido + % da economia certificada","Spend Radar como assinatura mensal (primeira receita recorrente do pilar)","Playbooks por fornecedor (Microsoft, Oracle, SAP, VMware, hyperscalers)","Benchmark de preços unitários acumulado (ativo proprietário)"],
 bench:"<b>Mercado:</b> KPMG ‘CIO Advisory’ com TBM (aliança Apptio) e otimização de custos "+E()+". <b>Diferencial A&M:</b> DNA de custo, success fee e execução da negociação "+Hy()+". Agentes de negociação já existem (Vertice: 18% de economia média em 4 mil negociações) "+E()+". Câmbio mais forte em 2026 abre janela para renegociar contratos em dólar "+Hy()+".",
 ev:"Fontes: IT Forum (FinOps 20–30%), Baguete (VMware 8–15×), ABES/IDC mar/2026, TI Inside fev/2025. Modelo de preço: proposta DTS."},
{id:"tech-tax-innovation-incentives",code:"1.6",pillar:1,st:"ai",name:"Tech Tax & Innovation Incentives",from:"Strategic Tech Tax / Accounting Planning + Innovation Tax Incentives Advisory",
 tagline:"Transformar tecnologia em benefício fiscal: Lei do Bem, capitalização e incentivos",
 pitch:"Um só produto para o lado fiscal e contábil da tecnologia: <b>enquadra projetos de software e IA na Lei do Bem</b>, capitaliza corretamente desenvolvimento e nuvem e reduz o custo líquido da transformação.",
 meta:["Ciclo anual (FormP&D até set.)","Comprador: CFO · Head Tax · CIO","Fixo + êxito sobre benefício","Em parceria com A&M Tax"],
 kpis:[["4,2 mil","empresas usaram a Lei do Bem (ano-base 2024) [E · MCTI]"],["R$ 51,6 bi","em PD&I declarados; ~14 mil projetos [E · MCTI]"],["−10%","corte linear nos incentivos desde 2026 (LC 224/2025) [E]"]],
 who:["Empresas com desenvolvimento relevante de software ou IA","CFOs que tratam TI só como despesa","Empresas implantando data centers (Redata)"],
 pain:["Incentivo subutilizado e documentação técnica fraca","Corte de 10% exige mais rigor no enquadramento","Capitalização inconsistente de software e de nuvem"],
 deliv:["Mapa de elegibilidade de projetos","Dossiê técnico por projeto (FormP&D)","Política de capitalização de software e nuvem","Cálculo do benefício e reconciliação","Suporte em fiscalização"],
 skills:["Tributário (A&M Tax)","Contabilidade (CPC 04 / IFRS)","Engenharia de software","Documentação técnica"],
 steps:[["M1","Varredura","Portfólio de projetos, Jira/Git e despesas de P&D"],["M1–2","Enquadramento","Inovação e risco tecnológico por projeto"],["M2–3","Dossiê","Relatórios técnicos e memória de cálculo"],["M3","Contabilização","Capitalização e política contábil"],["Anual","Defesa","Fiscalização e novo ciclo"]],
 tools:"Agente de enquadramento DTS (LLM sobre Jira, Confluence e Git), modelo de cálculo, repositório de evidências.",
 data:"Backlog e histórico de projetos, commits e documentação, timesheets, despesas de P&D, contratos de terceiros, balancete.",
 ai:["Lê histórias, commits e documentação para identificar inovação e risco tecnológico","Redige o rascunho do relatório técnico por projeto, com evidências","Cruza horas, pessoas e despesas para a memória de cálculo","Aponta fragilidades antes da entrega ao MCTI"],
 prodz:["Parceria com A&M Tax: o DTS entrega o lado técnico","Ciclo anual recorrente","Fixo de varredura + êxito sobre o benefício","Cross-sell com 1.5: o incentivo financia parte da modernização"],
 bench:"<b>Mercado:</b> KPMG tem área de Incentivos Fiscais com estudo sobre Lei do Bem "+E()+"; boutiques especializadas dominam o modelo de êxito "+Hy()+". <b>Diferencial:</b> leitura técnica do software com IA + integração com custo de TI "+Hy()+".",
 ev:"MCTI via Convergência Digital (ano-base 2024); LC 224/2025 via Correio Braziliense (ago/2026). Redata aprovado no Senado em set/2026 (sanção não verificada)."},
{id:"ai-value-governance-office",code:"1.7",pillar:1,st:"new",name:"AI Value & Governance Office",from:"Novo · produto com IA",
 tagline:"Do piloto ao P&L: a torre que governa valor, risco e custo da IA",
 pitch:"Escritório instalado e operado pela A&M que gerencia o <b>portfólio de IA</b> da empresa: prioriza, mede ROI, controla o custo de modelos e agentes e garante <b>governança responsável</b> (PL 2338, ISO/IEC 42001, LGPD).",
 meta:["Setup: 8 semanas","Operação: 6–12 meses","Comprador: CEO · CFO · CIO · CRO","Assinatura mensal por nível"],
 kpis:[["56%","dos CEOs sem retorno financeiro com IA [E · PwC 2026]"],["27%","das empresas no Brasil com governança de IA madura [E · Deloitte 2026]"],[">40%","dos projetos agênticos serão cancelados até 2027 [E · Gartner]"]],
 who:["Empresas com muitos pilotos de IA e pouco resultado","Conselhos e CROs preocupados com risco de IA","Setores regulados: financeiro, saúde, varejo com dados pessoais"],
 pain:["IA espalhada sem dono, métrica nem controle de custo","Risco regulatório e reputacional (marco de IA em votação; ANPD virou agência)","Agentes em produção sem inventário nem trilha de auditoria"],
 deliv:["Inventário de casos de uso, modelos e agentes","Painel de valor (ROI por caso) e de custo (tokens, nuvem)","Política e comitê de IA responsável","Classificação de risco e controles","Decisão mensal: escalar · ajustar · encerrar"],
 skills:["Gestão de portfólio","Finanças","Risco & compliance","Governança de IA","Engenharia de dados e IA"],
 steps:[["S1–2","Inventário","Casos de uso, modelos, agentes e fornecedores"],["S3–4","Régua de valor","KPIs por caso, linha de base e custo total"],["S5–6","Governança","Política, comitê, risco, controles"],["S7–8","Painel","Torre de valor e risco operando"],["Mensal","Operar","Escalar · ajustar · encerrar + relatório ao conselho"]],
 tools:"Painel DTS (Power BI/Fabric); registro de IA governado, migrável para plataformas de mercado (ex.: IBM watsonx.governance, OneTrust, Credo AI, ServiceNow AI Control Tower); FinOps de IA; LLM para avaliação.",
 data:"Lista de iniciativas e fornecedores de IA, logs de uso e custo de modelos, KPIs de negócio, políticas de dados, contratos.",
 ai:["Descobre uso de IA em contratos, faturas e logs (shadow AI)","Avalia casos de uso e agentes contra a política (testes adversariais assistidos)","Monitora custo por token e por resultado","Gera o relatório mensal ao conselho"],
 prodz:["Assinatura com 3 níveis: Essencial · Avançado · Regulado","Kit de governança pronto: política, RACI e avaliação de risco alinhados a ISO/IEC 42001 e NIST AI RMF","Painel reutilizável entre clientes","Divisão de papéis com a frente Data & IA da A&M: DTS governa, Data & IA constrói casos de negócio "+"(a alinhar)"],
 bench:"<b>Mercado:</b> KPMG ‘Trusted AI’ (1ª Big Four com ISO 42001) e Deloitte ‘Trustworthy AI’ focam risco "+E()+". MIT NANDA: 95% das organizações sem impacto mensurável em P&L com GenAI "+E("MIT NANDA via Fortune, ago/2025")+". <b>Diferencial A&M:</b> unir valor + governança + custo, com accountability de operador; coerente com a meta global da A&M de 50% da receita ligada a IA até 2028 "+E("Bloomberg mai/2026")+".",
 ev:"PwC CEO Survey 2026; Deloitte State of AI 2026; PL 2338 com votação prevista após as eleições de out/2026 (MobileTime ago/2026); Lei 15.352/2026 (ANPD agência)."},
/* ======================= PILAR 2 ======================= */
{id:"ai-sourcing-vendor-selection",code:"2.1",pillar:2,st:"ai",name:"AI-Accelerated Sourcing & Vendor Selection",from:"IT Sourcing (Software & Vendor) Selection",
 tagline:"Escolher e contratar tecnologia em menos tempo, com poder de negociação",
 pitch:"Seleção de software e fornecedores com requisitos, RFP, avaliação e negociação <b>aceleradas por IA</b>: decisão defensável em semanas e contrato com proteção de preço, câmbio e saída.",
 meta:["Duração: 5–8 semanas","Comprador: CIO · Compras · CFO","Preço fixo por categoria","Bônus por economia negociada"],
 kpis:[["15 dias","a menos no ciclo de compra com IA (Vertice) [E]"],["100%","requisitos rastreáveis até a decisão"],["3 cláusulas","câmbio · saída · reajuste sempre negociadas"]],
 who:["CIOs trocando ERP, CRM, motor fiscal ou ITSM","Compras de TI","Fundos de PE padronizando sistemas no portfólio"],
 pain:["RFPs de 3–6 meses","Decisões por relacionamento, sem trilha de auditoria","Contratos sem proteção cambial e com lock-in"],
 deliv:["Requisitos priorizados","RFP, long-list e short-list","Avaliação ponderada e provas roteirizadas","Negociação e term sheet","Recomendação ao comitê"],
 skills:["Análise de requisitos","Arquitetura","Negociação","Compras","IA aplicada"],
 steps:[["S1","Necessidade","Processos, requisitos e restrições"],["S2","Mercado","Long-list, short-list e RFP"],["S3–4","Avaliação","Respostas pontuadas e demos roteirizadas"],["S5–6","Negociação","Preço, SLAs, câmbio, saída"],["S7–8","Decisão","Recomendação e plano de contratação"]],
 tools:"Biblioteca DTS de requisitos por categoria, LLM para RFP e avaliação de respostas, matriz de scoring, base de preços do Spend Radar.",
 data:"Processos, requisitos, propostas de fornecedores, contratos atuais, benchmarks de preço.",
 ai:["Gera requisitos a partir de processos e documentos existentes","Monta a RFP e lê as respostas apontando lacunas e contradições","Compara cláusulas com o padrão DTS de contrato","Prepara o roteiro de negociação com alternativas"],
 prodz:["Catálogo de seleções padronizadas: ERP, CRM, motor fiscal, ITSM, HCM","Biblioteca de requisitos reaproveitável","Preço fixo por categoria + bônus por economia","Desdobra em 2.2 e 4.4"],
 bench:"<b>Mercado:</b> EY ‘Office of the CIO · Sourcing’ "+E()+"; ISG e Gartner em sourcing advisory "+Hy("não verificado")+". <b>Diferencial A&M:</b> independência (sem revenda) e negociação "+Hy()+".",
 ev:"Tempos e bônus: proposta DTS. Independência de fornecedor é o argumento central frente a integradores."},
{id:"erp-tax-reform-readiness",code:"2.2",pillar:2,st:"ai",name:"ERP & Tax Reform Readiness",from:"ERP Readiness & Gap Analysis",
 tagline:"ERP pronto para a Reforma Tributária e para o fim do SAP ECC",
 pitch:"Avalia e prepara o ERP e o ecossistema fiscal para a <b>Reforma Tributária (CBS/IBS, 2026–2033)</b> e para decisões de plataforma (S/4HANA, TOTVS, motor fiscal), com fit-gap acelerado por IA e mineração de processos.",
 meta:["Duração: 4–8 semanas","Comprador: CFO · CIO · Head Tax","Preço fixo por porte","Em parceria com A&M Tax"],
 kpis:[["01/01/2027","CBS plena: virada crítica dos sistemas [E · LC 214/2025]"],["2027","fim da manutenção padrão do SAP ECC, extensível a 2030 [E · Baguete]"],["37%","das empresas ainda no estágio inicial de adequação [E · PwC]"]],
 who:["Empresas com ERP legado ou muito customizado","Clientes SAP ECC","Médias empresas atrasadas na adequação"],
 pain:["Dois regimes em paralelo até 2033","Dados mestres e cadastros fiscais inconsistentes","Decisão ERP nativo × motor fiscal × troca de ERP sem base"],
 deliv:["Diagnóstico de prontidão fiscal e de ERP","Fit-gap de processos (fit-to-standard)","Decisão de arquitetura: ERP × motor fiscal","Plano de adequação e de cutover","Business case de upgrade ou troca"],
 skills:["ERP (SAP, TOTVS, Oracle)","Tributário","Processos","Arquitetura","Gestão de projetos"],
 steps:[["S1","Escopo","Entidades, operações e sistemas fiscais"],["S2–3","Fit-gap","Mineração de processos + análise de customizações"],["S3–4","Dados","Qualidade de dados mestres e cadastros fiscais"],["S5–6","Decisão","Arquitetura-alvo e business case"],["S7–8","Plano","Adequação e cutover"]],
 tools:"Mineração de processos (Celonis ou SAP Signavio, quando houver), análise de customizações com IA, checklist fiscal DTS, LLM sobre legislação e regulamentos (base revisada pelo Tax).",
 data:"Logs de transação do ERP, customizações (ex.: ABAP), cadastros, documentos fiscais eletrônicos, mapa de processos.",
 ai:["Lê customizações e documentação para estimar o esforço de adequação","Compara processos reais (logs) ao padrão do ERP","Gera casos de teste fiscais a partir das regras de CBS/IBS","Responde dúvidas do time sobre as regras, com fonte"],
 prodz:["Pacote ‘Reforma Pronta’ com escopo fixo por porte","Checklists e casos de teste reaproveitáveis","Desdobra em 2.3 (TMO) e 4.4 (Migration Assurance)","Janela: 4T26–2027 e 2ª onda em 2028–29 (IBS) "+"(proposta DTS)"],
 bench:"<b>Mercado:</b> as Big Four entram pelo Tax: EY Beyond Tax Analytics; KPMG com Thomson Reuters ONESOURCE; PwC e Deloitte com pesquisas "+E()+". TOTVS lançou a ‘Jornada da Reforma’ com chatbot de IA "+E()+". <b>Diferencial A&M:</b> o lado sistêmico (ERP, dados, cutover) "+Hy()+".",
 ev:"Cronograma: EC 132/2023, LC 214/2025, LC 227/2026, Decreto 12.955/2026. SAP ECC: Baguete. PwC ‘Tributos no centro’. 53,5% preferem apurar no ERP (Monitor Mercantil)."},
{id:"predictive-transformation-office",code:"2.3",pillar:2,st:"ai",name:"Predictive Transformation Office",from:"TMO + Modelo de Implantação e Governança",
 tagline:"Um PMO que antecipa o problema: governança de transformação com IA preditiva",
 pitch:"Escritório de transformação que integra <b>governança, implantação e captura de valor</b> e usa IA para ler status, cronogramas e riscos e <b>alertar antes</b> que o atraso vire crise.",
 meta:["Duração: 6–24 meses","Comprador: CEO · CIO · sponsor","Fee mensal por porte","Ponte para 2.4 se já houver crise"],
 kpis:[["+45%","estouro médio de orçamento em grandes projetos de TI [E · McKinsey/Oxford]"],["56%","menos valor entregue que o previsto [E · McKinsey/Oxford]"],["100%","das iniciativas com valor rastreado"]],
 who:["Programas de ERP, transformação digital e reestruturação","Empresas pós-fusão","Conselhos que querem visibilidade real"],
 pain:["Status ‘verde’ até virar vermelho","PMO burocrático sem accountability por resultado","Benefícios prometidos e não rastreados"],
 deliv:["Modelo de governança e implantação","Painel integrado (prazo, custo, risco, valor)","Alertas preditivos","Rituais de decisão","Relatórios ao conselho"],
 skills:["Gestão de programas","Governança","Analytics","Gestão de valor","Comunicação executiva"],
 steps:[["S1–2","Setup","Governança, papéis e cadências"],["S2–4","Integração","Jira, Azure DevOps, MS Project, ServiceNow, finanças"],["S4+","Operação","Rituais, decisões e controle de valor"],["Contínuo","Predição","Alertas de risco e cenários"],["Fim","Transferência","Internalização do modelo"]],
 tools:"Painel DTS (Power BI), conectores Jira/Azure DevOps/MS Project/ServiceNow SPM, LLM para leitura de status reports e atas.",
 data:"Cronogramas, backlogs, status reports, RAID logs, orçamento e benefícios.",
 ai:["Lê status, atas e backlogs e detecta sinais de risco (linguagem e tendência)","Projeta desvio de prazo e custo a partir do histórico","Gera atas e planos de ação","Responde perguntas do sponsor em linguagem natural"],
 prodz:["Funde TMO + Modelo de Implantação e Governança","Fee mensal por porte do programa","Painel e modelo de risco reutilizáveis","Base técnica do IMO/SMO (3.3)"],
 bench:"<b>Mercado:</b> integradores e Big Four oferecem PMO; concorrentes locais nativos em IA (CI&T, Falconi) levam IA à entrega "+E()+". <b>Diferencial:</b> foco em valor + predição + postura de operador "+Hy()+".",
 ev:"CI&T Flow e Falconi (R$ 100 mi em IA): IT Forum e Jornal do Comércio 2026. Alertas antecipados: meta de produto (proposta DTS)."},
{id:"tech-project-rescue",code:"2.4",pillar:2,st:"keep",sig:true,name:"Tech Project Rescue",from:"Project Remediation",
 tagline:"Turnaround de projetos de tecnologia em crise",
 pitch:"Intervenção rápida em <b>projetos de ERP, sistemas e transformação em crise</b>: diagnóstico forense em 2–3 semanas, decisão (recuperar, replanejar ou encerrar) e comando da recuperação.",
 meta:["Diagnóstico: 2–3 semanas","Recuperação: 3–9 meses","Comprador: CEO · CFO · conselho","Fixo + marcos"],
 kpis:[["2–3 sem.","para o diagnóstico forense"],[">70%","das iniciativas de ERP não atingirão o business case até 2027 [E · Gartner]"],["3 saídas","recuperar · replanejar · encerrar"]],
 who:["Empresas com ERP ou sistema atrasado e acima do orçamento","Conselhos e fundos preocupados com projetos críticos","Projetos de Reforma Tributária atrasados"],
 pain:["Custos crescentes e confiança perdida","Disputa com o integrador","Go-live arriscado"],
 deliv:["Diagnóstico forense: escopo, prazo, custo, qualidade, contrato","Decisão recomendada com cenários","Plano de recuperação e re-baseline","Gestão e renegociação do fornecedor","Comando da recuperação"],
 skills:["Gestão de crise","Gestão de programas","Contratos e disputas","Arquitetura","Negociação"],
 steps:[["S1","Triagem","Entrevistas, artefatos e contrato"],["S2–3","Forense","Escopo, código, testes e backlog"],["S3","Decisão","Cenários e recomendação ao conselho"],["M1–3","Recuperar","Re-baseline, governança, fornecedor"],["Go-live","Entregar","Estabilização"]],
 tools:"Kit forense DTS, LLM para leitura de artefatos (contratos, especificações, defeitos), análise de qualidade de código e testes, painel de recuperação.",
 data:"Contrato e aditivos, cronogramas, backlog, defeitos, código, atas e faturas do integrador.",
 ai:["Lê milhares de artefatos e reconstrói a linha do tempo das decisões","Cruza contrato × entregas para achar desvios e pleitos","Estima o custo real para terminar a partir de defeitos e testes","Simula cenários de recuperação"],
 prodz:["Diagnóstico forense com escopo e preço fixos (porta de entrada)","Playbook A&M de recuperação","Apoio a disputas com a área de Disputes & Investigations da A&M "+"(a alinhar)","Sinergia com 2.2 e 4.4"],
 bench:"<b>Mercado:</b> pares de turnaround e Big Four atuam em recuperação de projetos "+Hy("não verificado")+". <b>Diferencial A&M:</b> DNA de turnaround, produto-símbolo do pilar "+Hy()+".",
 ev:"Demanda: projetos de Reforma Tributária e ERP atrasados (KPMG/PwC/ABES). Produto mantido: forte direito de vencer."},
{id:"ai-adoption-change",code:"2.5",pillar:2,st:"ai",name:"AI Adoption & Change",from:"Gestão de Mudanças Tech",
 tagline:"Pessoas usando a tecnologia comprada, e a IA virando hábito",
 pitch:"Gestão de mudança orientada a dados para <b>adoção de sistemas e de IA</b> (copilotos, agentes, novos ERPs): mede o uso real, personaliza o apoio e comprova o ganho de produtividade.",
 meta:["Duração: 8–16 semanas","Comprador: CIO · CHRO · sponsor","Fixo + bônus por meta de adoção","Combina com 2.6"],
 kpis:[["44%","citam falta de conhecimento da equipe como obstáculo à IA [E · Cetic.br/TI Inside]"],["17%","das empresas (10+ empregados) usam IA [E · Cetic.br 2025]"],["semanal","medição de uso real"]],
 who:["Empresas que compraram copilotos de IA e não veem uso","Implantações de ERP e CRM","Reestruturações com nova forma de trabalhar"],
 pain:["Licenças de IA ociosas","Treinamentos genéricos","Resistência e medo de substituição"],
 deliv:["Diagnóstico de prontidão e personas","Plano de mudança e comunicação","Trilhas de capacitação por papel","Rede de campeões","Painel de adoção e produtividade"],
 skills:["Gestão de mudança (ADKAR)","Comunicação","Capacitação","Analytics","IA aplicada"],
 steps:[["S1–2","Prontidão","Personas, impactos e barreiras"],["S3–4","Desenho","Jornadas, trilhas e campeões"],["S5–12","Ativação","Ondas de adoção e comunicação"],["Contínuo","Medição","Telemetria de uso e pulso"],["Fim","Sustentação","Transferência e rituais"]],
 tools:"Telemetria de uso (ex.: Microsoft 365/Copilot analytics), plataformas de adoção digital quando houver (WalkMe, Whatfix), LLM para conteúdo personalizado, pesquisas de pulso.",
 data:"Logs de uso de ferramentas, pesquisas, perfis de cargo, indicadores de produtividade.",
 ai:["Gera trilhas e conteúdos por persona e cargo","Assistente de dúvidas 24/7 para usuários","Analisa telemetria e sentimento para direcionar ações","Mede ganhos de produtividade por caso de uso"],
 prodz:["Pacotes por tecnologia: ‘Copilot que funciona’, ‘ERP adotado’","Biblioteca de conteúdos e kit de campeões","Fixo + bônus por meta de adoção","Reposiciona ‘Gestão de Mudanças Tech’ para a era da IA"],
 bench:"<b>Mercado:</b> OCM é oferta comum em Big Four e integradores "+Hy("não verificado")+". <b>Diferencial A&M:</b> mudança medida por dados de uso de IA, com meta "+Hy()+".",
 ev:"Cetic.br TIC Empresas 2025; barreiras via TI Inside (jun/2026)."},
{id:"ai-native-it-productivity",code:"2.6",pillar:2,st:"new",name:"AI-Native IT Productivity",from:"Novo · produto com IA",
 tagline:"A TI que usa IA em si mesma: desenvolvimento, service desk e operações",
 pitch:"Programa que implanta <b>IA e agentes dentro da própria TI</b> (engenharia de software, service desk e operações) com linha de base, ganhos medidos e guardrails, liberando capacidade e reduzindo custo.",
 meta:["Piloto: 10 semanas","Escala: ondas trimestrais","Comprador: CIO · CTO","Fixo + bônus por ganho medido"],
 kpis:[["3 frentes","SDLC · service desk · operações (AIOps)"],["10 sem.","do baseline ao piloto medido"],["25 mil","agentes de IA trabalhando ao lado de ~40 mil pessoas na McKinsey [E · McKinsey via BI/HBR, jan/2026]"]],
 who:["CIOs pressionados a mostrar IA na própria área","TIs com backlog alto","Service desks caros ou terceirizados"],
 pain:["Ferramentas de IA compradas sem método","Produtividade não medida","Risco de qualidade, segurança e propriedade intelectual no código gerado"],
 deliv:["Linha de base de produtividade (fluxo, DORA, tickets)","Pilotos em SDLC, service desk e operações","Guardrails de segurança, qualidade e PI","Business case de escala","Playbook e capacitação"],
 skills:["Engenharia de software","ITSM","AIOps","Gestão de mudança","Segurança"],
 steps:[["S1–2","Baseline","Métricas DORA e de fluxo, tickets e custos"],["S3–4","Casos","Priorização por valor e risco"],["S5–8","Pilotos","Assistentes de código, agentes de service desk, AIOps"],["S9–10","Medição","Ganhos e qualidade"],["Escala","Rollout","Ondas e governança contínua"]],
 tools:"Assistentes de código (ex.: GitHub Copilot, Claude Code, Gemini Code Assist), agentes de ITSM (ServiceNow, Jira Service Management), observabilidade/AIOps, painel DTS de produtividade.",
 data:"Repositórios e pipelines, tickets, incidentes, métricas DORA, custos de terceiros.",
 ai:["É o próprio objeto do produto: IA no ciclo de software e na operação","Agentes resolvem tickets de nível 1 e sugerem soluções","Causa-raiz de incidentes assistida","Medição automática de produtividade e qualidade"],
 prodz:["Piloto padronizado de 8 semanas com métricas fixas","Playbook de guardrails reaproveitável","Fixo + bônus sobre capacidade liberada e medida","Alimenta 1.4 (op model) e 1.5 (custo)"],
 bench:"<b>Mercado:</b> integradores vendem produtividade com IA atrelada à própria entrega (ex.: CI&T Flow) "+E()+". <b>Diferencial A&M:</b> medição independente e conversão do ganho em custo ou capacidade "+Hy()+".",
 ev:"Deloitte Tech Trends 2026 (fonte secundária): 11% com agentes em produção, 38% em piloto. Bônus por ganho: proposta DTS."},
/* ======================= PILAR 3 ======================= */
{id:"ai-tech-due-diligence",code:"3.1",pillar:3,st:"ai",sig:true,name:"AI-Powered Tech Due Diligence",from:"IT Due Diligence (Buy Side) + IT Due Diligence (Sell Side)",
 tagline:"Red flag em 1 semana, DD completa em 3: código, dados, cyber e IA no mesmo relatório",
 pitch:"Due diligence de tecnologia para <b>compradores (buy-side)</b> e <b>vendedores (sell-side e vendor readiness)</b>, com IA lendo o data room e varrendo código, e avaliação específica dos <b>ativos e riscos de IA</b> do alvo.",
 meta:["Duração: 1–4 semanas por nível","Comprador: PE · corporate M&A · bancos","Preço fixo por nível","Programa anual para fundos"],
 kpis:[["50%","dos deals no Brasil com PE/VC em 2025 [E · KPMG]"],["274","deals de TI no 1S26: setor nº 1 [E · KPMG]"],[">75%","menos tempo de avaliação de código em DD com CAST Highlight (caso EY) [E]"]],
 who:["Fundos de PE e family offices","Corporate development","Vendedores preparando a saída","Bancos de investimento"],
 pain:["Prazos de deal curtos e data rooms enormes","Riscos ocultos: dívida técnica, cyber, licenças, pessoas-chave","IA ‘de fachada’ no alvo, que infla o valuation"],
 deliv:["Red flags e impacto no valuation","Custos de standalone, capex de recuperação e sinergias","Avaliação de código e arquitetura","Diligência de IA e dados","Plano de 100 dias (buy) ou Vendor DD report (sell)"],
 skills:["Arquitetura","Engenharia de software","Cyber","Finanças de deal","IA aplicada"],
 steps:[["D1–3","Data room","Ingestão e triagem por IA"],["D3–10","Análise","Entrevistas com a gestão e varredura de código"],["D7–14","Quantificar","Custos, capex, riscos e sinergias"],["D14–20","Relatório","Red flags e recomendações"],["Pós","100 dias","Ponte para 3.2 e 3.4"]],
 tools:"Análise de código (ex.: CAST Highlight, Sema, SonarQube, Black Duck), LLM sobre o VDR (Datasite, Intralinks), checklist DTS, modelo de custos de standalone.",
 data:"Data room (contratos, arquitetura, políticas), repositórios de código, inventários, histórico de incidentes de cyber, custos de TI.",
 ai:["Lê o data room e monta o mapa de achados com referência à fonte","Varre código: dívida técnica, licenças open source, vulnerabilidades","Avalia a capacidade real de IA do alvo (AI diligence)","Rascunha o relatório e as perguntas para a gestão"],
 prodz:["Três níveis com preço fixo: Red flag (1 sem.) · Completa (3 sem.) · Sell-side readiness","Checklists e modelo de custos padronizados","Programa anual com desconto por volume para fundos","Gatilho para 3.2, 3.4 e 3.5"],
 bench:"<b>Mercado:</b> Deloitte ‘M&A Technology’; EY-Parthenon ‘Transaction Strategy & Execution · Technology’; PwC ‘AI technology diligence’, ‘Harvey, powered by PwC’ e exclusividade com a ToltIQ (jun/2026) "+E()+". Bain replica o software do alvo com Claude Code; DiligenceSquared faz DD com agentes por ~US$ 50 mil "+E("FT/TechCrunch 2026")+". <b>Ativos A&M já existentes:</b> A&M Assist e DiligenceGPT "+E("A&M 2025")+". <b>Diferencial A&M:</b> DD com IA virou padrão; o diferencial migra para DD + 100 dias + execução "+Hy()+".",
 ev:"KPMG pesquisas de M&A 2025 e 1S26; PwC press releases (jul/2025; jun/2026)."},
{id:"integration-separation-blueprint",code:"3.2",pillar:3,st:"ai",name:"Integration & Separation Blueprint",from:"IT Integration & Separation Planning + IT Separation Strategy & Design",
 tagline:"Dia 1 sem susto: desenho de integração ou carve-out de TI, TSAs e custos",
 pitch:"Desenha a <b>TI do Dia 1 e do estado-alvo</b> em integrações e separações: estratégia, inventário de aplicações e infraestrutura, <b>TSAs</b>, custos de standalone e cronograma, com IA acelerando o mapeamento.",
 meta:["Duração: 4–8 semanas","Comprador: comprador/vendedor · PE","Preço fixo por complexidade","Gatilho para 3.3"],
 kpis:[["50–60%","das iniciativas de sinergia dependem fortemente de TI [E · McKinsey]"],["100%","serviços compartilhados cobertos por TSA"],["até 2027","separação Raízen Energia × Combustíveis anunciada [E · Forbes]"]],
 who:["Compradores estratégicos em fusões (ex.: MBRF)","Grupos em separação ou carve-out","Fundos comprando divisões"],
 pain:["Sistemas entrelaçados entre as partes","TSAs longas e caras","Custos de standalone subestimados"],
 deliv:["Estratégia de integração ou separação de TI","Inventário e disposição de aplicações (manter, migrar, clonar)","Escopo e preço de TSAs","Custos de standalone e one-off","Plano de Dia 1 e Dia 100"],
 skills:["Arquitetura","M&A","Contratos (TSA)","Infraestrutura","Gestão de programas"],
 steps:[["S1","Princípios","Tese do deal e estratégia de TI"],["S2–3","Inventário","Aplicações, dados, infra, contratos"],["S4–5","Disposição","Opção por sistema e TSAs"],["S6–7","Custos","Standalone, one-off, sinergias"],["S8","Plano","Dia 1 e Dia 100"]],
 tools:"Modelo de inventário DTS, LLM para contratos (cessão e change of control), ferramentas de EA quando houver (LeanIX, Ardoq), templates de TSA.",
 data:"Inventários, contratos de software, diagramas de arquitetura, custos.",
 ai:["Extrai cláusulas de change of control e cessão de centenas de contratos","Consolida inventários de fontes heterogêneas","Sugere a disposição por sistema com base em padrões","Rascunha os schedules de TSA"],
 prodz:["Funde ‘Integration & Separation Planning’ + ‘Separation Strategy & Design’","Templates de TSA e inventário reaproveitáveis","Preço fixo por complexidade","Desdobra em 3.3 (IMO/SMO)"],
 bench:"<b>Mercado:</b> Deloitte ‘Separation & Carve-out’ e serviços ACDC; EY-Parthenon TSE (carve-out, TSA, Dia 1) "+E()+". <b>Diferencial A&M:</b> tradição em carve-outs e reestruturações "+Hy()+".",
 ev:"Casos públicos: MBRF (concluída set/2025), Petz+Cobasi (Cade dez/2025), Braskem (controle IG4 abr/2026), Raízen (separação até 2027)."},
{id:"integration-separation-office",code:"3.3",pillar:3,st:"keep",name:"Integration & Separation Office (IMO/SMO)",from:"IT Integration Management Office + IT Separation Management Office",
 tagline:"Executar o Dia 1 e sair das TSAs no prazo",
 pitch:"IMO/SMO de TI que <b>comanda a execução</b> de integrações e separações: cutover, saída de TSAs, migrações e captura de sinergias, com governança única.",
 meta:["Duração: 3–18 meses","Comprador: comprador/vendedor · PE","Fee mensal + marcos","Bônus por saída de TSA no prazo"],
 kpis:[["0","interrupções críticas no Dia 1 (meta)"],["TSA","encerrada no prazo contratado"],["1 painel","marcos, riscos e sinergias"]],
 who:["Empresas entre signing e closing","Vendedores com obrigações de TSA","Fundos em estratégia de buy-and-build"],
 pain:["Execução fragmentada entre fornecedores","TSA estendida custa caro","Sinergias que não aparecem"],
 deliv:["Governança IMO/SMO","Plano integrado e cutover","Gestão de TSAs (entrada e saída)","Controle de sinergias","Relatórios ao comitê do deal"],
 skills:["Gestão de programas","M&A","Infraestrutura","Gestão de fornecedores","Comunicação"],
 steps:[["S1–2","Mobilizar","Governança e plano integrado"],["Até D1","Dia 1","Cutover e ensaios"],["D1–100","Estabilizar","Hypercare e quick wins"],["M3–18","Saída de TSA","Migrações e encerramento"],["Fim","Sinergias","Comprovação e transferência"]],
 tools:"Painel do Predictive Transformation Office (2.3) adaptado a deals, runbooks de cutover, controle de TSA.",
 data:"Plano integrado, TSAs, inventários, custos e sinergias.",
 ai:["Reaproveita a predição de risco do 2.3 no cutover","Gera runbooks e checklists a partir do blueprint","Monitora consumo e custo de TSA","Resume o status ao comitê do deal"],
 prodz:["Funde IMO + SMO: mesmo método, duas direções","Runbooks reutilizáveis","Fee mensal + bônus por saída de TSA no prazo","Combina com 3.4"],
 bench:"<b>Mercado:</b> Big Four oferecem IMO/SMO "+E()+". <b>Diferencial A&M:</b> postura de operador em carve-outs complexos "+Hy()+".",
 ev:"Produto mantido (execução intensiva em pessoas seniores). IA é acessória."},
{id:"tech-value-creation-plan",code:"3.4",pillar:3,st:"keep",name:"Tech Value Creation Plan",from:"IT Synergies & Value Creation",
 tagline:"Sinergias e alavancas de tecnologia que viram EBITDA",
 pitch:"Identifica, valida e acompanha <b>sinergias e alavancas de valor de tecnologia</b> pós-deal (custo, receita e capacidades) e as transforma em plano de 100 dias e metas para a gestão.",
 meta:["Duração: 4–6 semanas + acompanhamento","Comprador: PE · corporate","Fixo + êxito","Recorrência via 3.5"],
 kpis:[["100 dias","plano de captura"],["em R$","sinergia por alavanca, com dono"],["R$ 485 mi/ano","sinergias anunciadas na MBRF [E · Giro News]"]],
 who:["Fundos de PE após a aquisição","Corporações em integração","Empresas preparando a saída (equity story de tecnologia)"],
 pain:["Sinergias de TI estimadas no deal sem plano de captura","Valor de tecnologia ausente da tese de saída"],
 deliv:["Baseline e alavancas","Plano de 100 dias","Metas e donos","Acompanhamento da captura","Equity story de tecnologia para a saída"],
 skills:["Finanças de deal","Estratégia","TBM","Gestão de valor"],
 steps:[["S1–2","Baseline","Custos e capacidades"],["S2–4","Alavancas","Custo, receita digital, IA"],["S5–6","Plano","100 dias, metas e donos"],["Trimestral","Captura","Acompanhamento"],["Saída","Equity story","Narrativa de tecnologia"]],
 tools:"Modelo de sinergias DTS, Spend Radar, painel de captura.",
 data:"Custos de TI, contratos, headcount, roadmap e metas do plano de negócios.",
 ai:["Gera hipóteses de sinergia a partir de inventários e contratos das partes","Encontra sobreposição de fornecedores e licenças","Monitora a captura com dados financeiros","Rascunha a equity story"],
 prodz:["Modelo de sinergias padronizado por setor","Fixo + êxito sobre a sinergia capturada","Recorrência via 3.5 (Radar)","Mantém a essência do ‘IT Synergies & Value Creation’"],
 bench:"<b>Mercado:</b> comum em Big Four e estratégia (PE value creation) "+Hy("não verificado")+". <b>Diferencial A&M:</b> alinhamento à prática de Private Equity Performance Improvement "+Hy()+".",
 ev:"MBRF: Giro News (2025). Produto mantido."},
{id:"pe-tech-value-radar",code:"3.5",pillar:3,st:"new",name:"PE Tech Value Radar",from:"Novo · produto com IA (absorve o IT M&A Playbook como ativo)",
 tagline:"Saúde de tecnologia e de IA de todo o portfólio do fundo, sempre ligada",
 pitch:"Assinatura para fundos de PE que <b>monitora continuamente</b> tecnologia, cyber, custos e prontidão para IA de cada investida, com o <b>IT M&A Playbook</b> embutido para entrada, criação de valor e saída.",
 meta:["Assinatura anual por fundo","Comprador: sócios de operações de PE","Preço por empresa monitorada","Upsell de projetos A&M"],
 kpis:[["50%","do M&A brasileiro com PE/VC [E · KPMG 2025]"],["trimestral","Tech Health Score por investida"],["1 tela","portfólio inteiro comparável"]],
 who:["Gestoras de PE e VC (sócios de operações)","Family offices com holding de empresas","Conselhos de holdings"],
 pain:["Visibilidade desigual de tecnologia entre investidas","Cyber e dívida técnica descobertos tarde","Preparação de saída em cima da hora"],
 deliv:["Tech Health Score trimestral por investida","Alertas de risco (cyber, contratos, pessoas-chave)","Benchmark entre investidas","Plano de ação e acionamento de produtos A&M","Exit readiness"],
 skills:["Finanças de PE","Arquitetura","Cyber","Analytics","IA aplicada"],
 steps:[["M1","Onboarding","Questionário + coleta leve de dados por investida"],["M1–2","Score","Tech Health Score e benchmark"],["Trimestral","Revisão","Comitê com sócios do fundo"],["Sob demanda","Ação","DD, Value Creation, Spend, Interim"],["Pré-saída","Readiness","Vendor DD pronto"]],
 tools:"Plataforma DTS (formulário + conectores + Power BI), ferramentas de mercado de rating externo de cyber, LLM para leitura de documentos das investidas.",
 data:"Questionários trimestrais, dados financeiros de TI, contratos-chave, sinais externos de cyber, incidentes.",
 ai:["Lê relatórios e documentos de cada investida e extrai indicadores","Pontua, compara e explica variações automaticamente","Alerta mudanças relevantes (contratos, incidentes, vagas-chave)","Gera o book trimestral do fundo"],
 prodz:["Primeiro produto 100% recorrente do DTS","IT M&A Playbook deixa de ser produto e vira o motor do Radar","Preço por empresa monitorada + upsell de projetos","Relacionamento contínuo com o canal mais estratégico da A&M (PE) "+"(proposta DTS)"],
 bench:"<b>Mercado:</b> não foi encontrado produto equivalente em formato de assinatura entre as Big Four no Brasil "+Hy("não verificado")+"; ratings de cyber cobrem só cyber "+Hy()+".",
 ev:"Produto novo: hipótese a validar em 3–5 entrevistas com sócios de operações de fundos."},
/* ======================= PILAR 4 ======================= */
{id:"ai-ready-enterprise-architecture",code:"4.1",pillar:4,st:"ai",name:"AI-Ready Enterprise Architecture",from:"Strategy Architecture",
 tagline:"Arquitetura-alvo que sustenta dados e IA, com a dívida técnica em R$",
 pitch:"Define a <b>arquitetura-alvo de negócio, aplicações, dados e integração</b> pronta para IA, quantifica a <b>dívida técnica</b> em R$ e organiza a governança de arquitetura, com inventário gerado por IA.",
 meta:["Duração: 6–8 semanas","Comprador: CIO · CTO · Arquitetura","Preço fixo","Repositório vivo: assinatura opcional"],
 kpis:[["em R$","dívida técnica quantificada"],["6–8 sem.","para a arquitetura-alvo"],["1 repositório","vivo de arquitetura"]],
 who:["Empresas com arquitetura fragmentada","Quem quer escalar IA e esbarra em dados e integração","Pós-fusão"],
 pain:["Sem visão única de sistemas","Integrações ponto a ponto","Dados que não estão prontos para IA"],
 deliv:["Arquitetura atual: inventário e mapa","Arquitetura-alvo, incluindo plataforma de dados e IA","Dívida técnica quantificada","Princípios e governança de arquitetura","Roadmap de transição"],
 skills:["Arquitetura corporativa (TOGAF)","Dados","Integração","Cloud","IA"],
 steps:[["S1–2","Descobrir","Inventário assistido por IA"],["S3–4","Avaliar","Dívida técnica, dados, integração"],["S5–6","Desenhar","Arquitetura-alvo e plataforma de IA"],["S7–8","Transição","Roadmap e governança"],["Contínuo","Manter","Repositório vivo"]],
 tools:"Ferramentas de EA (ex.: SAP LeanIX, Ardoq, Bizzdesign), análise estática de código, LLM para documentação e diagramas.",
 data:"Inventários e CMDB, diagramas, documentação técnica, código, logs de integração, catálogo de dados.",
 ai:["Monta o inventário a partir de documentos, CMDB e código","Gera diagramas e documentação faltante","Estima e prioriza a dívida técnica","Avalia a prontidão dos dados para casos de IA"],
 prodz:["Renomeia ‘Strategy Architecture’, nome pouco claro ao mercado","Metamodelo e templates DTS","Preço fixo; manutenção do repositório como assinatura","Base para 4.2, 4.6 e 1.2"],
 bench:"<b>Mercado:</b> Deloitte ‘Technology Strategy & Architecture’ e EY (arquitetura corporativa no TST) "+E()+". Ferramentas de EA já embarcam agentes (SAP LeanIX AI Agent Hub; Ardoq diz automatizar ~40% do trabalho rotineiro) "+E("Ardoq/SAP")+". <b>Diferencial A&M:</b> arquitetura ligada a valor e IA "+Hy()+".",
 ev:"Renomeação proposta: ‘Strategy Architecture’ não comunica o que é entregue (proposta DTS)."},
{id:"application-portfolio-rationalization",code:"4.2",pillar:4,st:"ai",name:"Application Portfolio Rationalization",from:"Strategy Application",
 tagline:"Menos sistemas, menos custo, mais clareza",
 pitch:"Racionaliza o <b>portfólio de aplicações</b> (tolerar, investir, migrar, eliminar) com dados de uso, custo e valor, liberando orçamento para modernização e IA.",
 meta:["Duração: 6–8 semanas","Comprador: CIO · CFO","Fixo + êxito opcional","Combina com 1.5 e 4.6"],
 kpis:[["TIME","tolerar · investir · migrar · eliminar"],["em R$","economia por aplicação aposentada"],["6–8 sem.","decisão por aplicação"]],
 who:["Empresas com centenas de aplicações","Pós-fusão","Preparação para cloud ou novo ERP"],
 pain:["Aplicações redundantes","Licenças e manutenção caras","Shadow IT"],
 deliv:["Inventário com custo, uso e valor","Classificação TIME","Plano de aposentadoria e consolidação","Business case","Governança de portfólio"],
 skills:["Gestão de portfólio de aplicações","Finanças de TI","Arquitetura","Analytics"],
 steps:[["S1–2","Inventário","Coleta e descoberta"],["S3–4","Avaliação","Valor de negócio × saúde técnica × custo"],["S5–6","Decisão","TIME por aplicação"],["S7–8","Plano","Ondas e business case"],["Contínuo","Governar","Portfólio vivo"]],
 tools:"LeanIX ou ServiceNow APM quando houver, logs de SSO e uso, Spend Radar, LLM.",
 data:"Inventário, logs de acesso (SSO), custos e licenças, avaliação de usuários.",
 ai:["Descobre aplicações via contratos, faturas e logs de SSO","Classifica funcionalidades e detecta redundâncias","Sugere a classificação TIME com justificativa","Calcula o business case"],
 prodz:["Renomeia ‘Strategy Application’","Método TIME e scoring padronizados","Fixo + êxito opcional","Combina com 1.5 (economia) e 4.6 (modernização)"],
 bench:"<b>Mercado:</b> oferta comum em integradores e Big Four "+Hy("não verificado")+". <b>Diferencial A&M:</b> ligada à captura de custo "+Hy()+".",
 ev:"Renomeação e modelo: proposta DTS."},
{id:"cloud-ai-infrastructure-economics",code:"4.3",pillar:4,st:"ai",name:"Cloud & AI Infrastructure Economics",from:"Infrastructure Management",
 tagline:"Infraestrutura certa para a era da IA: nuvem, VMware, GPU e FinOps",
 pitch:"Decide e otimiza a <b>infraestrutura</b> (nuvem, data center, saída de VMware, capacidade para IA) pelo custo total e pelo risco, com <b>FinOps para nuvem e IA</b>.",
 meta:["Duração: 6–10 semanas","Comprador: CIO · CFO · Infra","Fixo + % de economia","Integra com 1.5"],
 kpis:[["8–15×","alta de licenças VMware pós-Broadcom [E · Baguete]"],["R$ 3,9 bi","bancos em migração para cloud em 2026, +30% [E · Febraban]"],["20–30%","otimização de nuvem com FinOps maduro [E · IT Forum]"]],
 who:["Empresas com VMware e data center próprio","Gasto de nuvem crescente","Quem planeja capacidade de IA ou data centers (Redata)"],
 pain:["Virtualização e nuvem fora de controle","Decisões de cloud sem TCO","Custo de IA (GPU e tokens) imprevisível"],
 deliv:["TCO e cenários: cloud, híbrido, on-prem","Plano de saída ou renegociação de VMware","Estratégia de capacidade para IA","Modelo de FinOps","Roadmap de migração"],
 skills:["Infraestrutura","Cloud","FinOps","Negociação","Finanças"],
 steps:[["S1–2","Linha de base","Inventário e custos"],["S3–4","Cenários","TCO e risco"],["S5–6","Decisão","Estratégia e VMware"],["S7–8","FinOps","Modelo e quick wins"],["S9–10","Roadmap","Migração e capacidade de IA"]],
 tools:"Ferramentas de descoberta de hyperscalers, APIs de custo de nuvem, ferramentas de FinOps, modelo de TCO DTS.",
 data:"Inventário de servidores e VMs, contratos, faturas, utilização, planos de IA.",
 ai:["Analisa utilização e recomenda right-sizing","Projeta custo de cargas de IA (tokens e GPU)","Lê contratos de infraestrutura e renovação","Simula cenários de TCO"],
 prodz:["Reposiciona ‘Infrastructure Management’, que soava como serviço gerenciado","Modelo de TCO e playbook VMware reaproveitáveis","Fixo + % de economia","Integra com o Spend Radar (1.5)"],
 bench:"<b>Mercado:</b> hyperscalers barateiam a execução: AWS Transform faz migração sem custo e cobra US$ 0,035 por minuto de agente em transformações customizadas "+E("AWS, set/2026")+"; KPMG com TBM "+E()+". <b>Diferencial A&M:</b> independência de fornecedor e foco em custo "+Hy()+".",
 ev:"Baguete (VMware), Febraban/Deloitte 2026 (Forbes jun/2026), IT Forum (FinOps)."},
{id:"complex-migration-assurance",code:"4.4",pillar:4,st:"keep",name:"Complex Migration Assurance",from:"Complex Migrations Support",
 tagline:"Garantia independente para migrações que não podem dar errado",
 pitch:"Assurance independente de <b>migrações complexas</b> (ERP, dados, cloud, core): qualidade, reconciliação de dados, prontidão de go-live e gestão do integrador.",
 meta:["Duração: a da migração","Comprador: CIO · CFO · conselho","Fee mensal por fase","Complementa 2.2, 3.3 e 4.6"],
 kpis:[["100%","dos dados críticos reconciliados"],["Go/No-go","com critérios objetivos"],["1 voz","independente do integrador"]],
 who:["Empresas migrando ERP ou core","Bancos e seguradoras","Pós-fusão consolidando sistemas"],
 pain:["O integrador avalia o próprio trabalho","Perda ou inconsistência de dados","Go-lives arriscados"],
 deliv:["Plano de assurance e critérios","Reconciliação de dados","Revisões de qualidade e testes","Prontidão de go-live","Relatórios ao comitê"],
 skills:["Migração de dados","Testes e QA","Arquitetura","Gestão de fornecedores"],
 steps:[["Início","Plano","Critérios e checkpoints"],["Build","Qualidade","Revisões e testes"],["Cargas","Dados","Reconciliação automatizada"],["Pré-go-live","Prontidão","Go/No-go"],["Hypercare","Estabilizar","Acompanhamento"]],
 tools:"Ferramentas de reconciliação de dados, scripts de comparação assistidos por IA, painel DTS.",
 data:"Dados de origem e destino, planos de teste, defeitos, cronogramas.",
 ai:["Gera regras de reconciliação e compara volume e conteúdo","Analisa defeitos e padrões de falha","Gera casos de teste a partir de regras de negócio","Resume a prontidão para o comitê"],
 prodz:["Reposiciona ‘Complex Migrations Support’ como assurance","Checklists de go-live e regras de reconciliação reutilizáveis","Fee mensal por fase","Complementa 2.2, 3.3 e 4.6"],
 bench:"<b>Mercado:</b> integradores executam a migração; assurance independente é nicho "+Hy("não verificado")+".",
 ev:"Produto mantido com reposicionamento de nome e promessa."},
{id:"it-resilience-recovery",code:"4.5",pillar:4,st:"ai",name:"IT Resilience & Recovery",from:"IT Resilience & Business Continuity Planning (vem do Pilar 1)",
 tagline:"Continuar operando quando a tecnologia falha, e voltar rápido",
 pitch:"Resiliência operacional e de tecnologia: <b>BIA, continuidade, recuperação de desastres e de ataques</b>, risco de terceiros de TI e simulações de crise com IA, alinhados à CMN 4.893 alterada pela 5.274.",
 meta:["Duração: 6–10 semanas","Exercícios anuais","Comprador: CIO · CRO · COO","Fixo + recorrência"],
 kpis:[["~R$ 800 mi","desviados no ataque à C&M Software (jul/2025) [E · Jornal Opção/Finsiders]"],["R$ 710 mi","no ataque à Sinqia (ago/2025) [E · Tecnoblog]"],["CMN 5.274","endurece cyber e cloud no financeiro (dez/2025) [E · Legisweb]"]],
 who:["Instituições financeiras e participantes do Pix","Varejo e indústria com operação crítica","Empresas após incidentes"],
 pain:["Planos de continuidade só no papel","Dependência crítica de terceiros de TI","Ransomware e ataques à cadeia de fornecedores"],
 deliv:["BIA e mapa de serviços críticos","Estratégia de continuidade e DR","Avaliação de risco de terceiros de TI","Exercícios de crise (tabletop)","Plano de recuperação de incidente"],
 skills:["Continuidade e DR","Cyber","Gestão de crise","Infraestrutura","Regulação"],
 steps:[["S1–2","BIA","Serviços críticos e dependências"],["S3–4","Lacunas","DR, backups e terceiros"],["S5–6","Estratégia","Planos e investimentos"],["S7–8","Exercício","Tabletop com cenários gerados por IA"],["Anual","Ciclo","Testes e atualização"]],
 tools:"Simulador de crise DTS (cenários com IA), ferramentas de BIA, mapeamento de dependências (CMDB), ratings de cyber de terceiros.",
 data:"CMDB, contratos de terceiros, planos existentes, incidentes, requisitos regulatórios.",
 ai:["Gera cenários de crise realistas e injeções em tempo real no tabletop","Mapeia dependências a partir de CMDB e documentos","Avalia contratos de terceiros: SLA, cyber, saída","Mantém os planos atualizados"],
 prodz:["Muda de pilar: resiliência é arquitetura","Biblioteca de cenários de crise por setor","Exercícios anuais como recorrência","Ponte com as práticas de crise da A&M "+"(a alinhar)"],
 bench:"<b>Mercado:</b> Big Four têm práticas fortes de cyber e resiliência "+Hy("não verificado")+". <b>Diferencial A&M:</b> experiência em gestão de crise real "+Hy()+".",
 ev:"Jornal Opção/Finsiders (C&M), Tecnoblog (Sinqia), Legisweb (CMN 5.274)."},
{id:"legacy-xray-ai-modernization",code:"4.6",pillar:4,st:"new",name:"Legacy X-Ray & AI Modernization",from:"Novo · produto com IA",
 tagline:"Raio-X do legado com IA generativa e modernização com risco controlado",
 pitch:"Usa IA para <b>ler e documentar sistemas legados</b> (COBOL, PL/SQL, Delphi, ABAP, .NET), extrair regras de negócio e montar o <b>business case de modernização</b>; depois orquestra fábricas e ferramentas agênticas com assurance independente.",
 meta:["Raio-X: 4–6 semanas","Modernização: por ondas","Comprador: CIO · CTO · CFO","Fixo + assurance mensal"],
 kpis:[["R$ 50,4 bi","orçamento de tecnologia dos bancos em 2026 [E · Febraban]"],["neutro","em fornecedor: seleciona e garante, não revende"],["até 4×","mais rápido em migração .NET com AWS Transform [E · AWS]"]],
 who:["Bancos e seguradoras com mainframe (ex.: modernização contínua em Bradesco e Caixa)","Governo e utilities","Indústrias com ERP muito customizado"],
 pain:["Sistemas que ninguém mais entende","Conhecimento concentrado em poucas pessoas","Modernizações caras que falham"],
 deliv:["Raio-X: inventário, dependências e complexidade","Regras de negócio documentadas","Estratégia por módulo: re-host, refactor, replace","Business case e roadmap","Assurance da execução (com 4.4)"],
 skills:["Engenharia de software legado","Arquitetura","IA generativa","Finanças","Gestão de fornecedores"],
 steps:[["S1","Ingestão","Código, JCL, banco e documentação"],["S2–3","Raio-X","IA gera mapas, documentação e regras"],["S4–5","Estratégia","Opção por módulo e business case"],["S6","Seleção","Fábrica ou ferramenta e piloto"],["Execução","Assurance","Qualidade e equivalência funcional"]],
 tools:"Ferramentas agênticas de modernização (ex.: AWS Transform, IBM watsonx Code Assistant for Z, GitHub Copilot app modernization, Claude Code), análise estática, LLM corporativo em ambiente seguro.",
 data:"Código-fonte, JCL, esquemas de banco, documentação, logs de execução.",
 ai:["Lê código legado e gera documentação e diagramas","Extrai regras de negócio rastreáveis até o código","Estima esforço e risco por módulo","Gera testes de equivalência funcional para validar a modernização"],
 prodz:["Raio-X com escopo e preço fixos por volume de código","Neutro em fornecedor: a A&M seleciona e garante, não revende","Assurance mensal na execução","Alimenta 4.1, 4.2 e 4.4"],
 bench:"<b>Mercado:</b> McKinsey LegacyX, Accenture GenWizard, IBM watsonx Code Assistant for Z e Bob, AWS Transform, GitHub Copilot app modernization; Anthropic promete COBOL ‘em trimestres, não anos’ (fev/2026) "+E()+". <b>Diferencial A&M:</b> a execução vira commodity; o valor migra para rota, business case e assurance independente "+Hy()+".",
 ev:"Bradesco e Caixa: Convergência Digital; Febraban/Deloitte 2026."}
];

/* ---------- TIMELINE · IA nas consultorias (benchmark) ---------- */
const TL_MARKET=[
 {d:"Set 2023",s:"EY.ai",t:"EY lança EY.ai após investir US$ 1,4 bi",x:"Plataforma e assistente interno (EYQ). Começa a corrida das Big Four por plataformas próprias de IA.",src:"ICMIF, set/2023",tag:"Big Four"},
 {d:"Mar 2025",s:"Zora · agent OS",t:"Deloitte Zora AI, PwC agent OS e EY.ai Agentic",x:"Agentes por função vendidos por <b>assinatura</b> (Deloitte), orquestração multi-fornecedor (PwC) e 150 agentes de tributos (EY).",src:"SiliconANGLE 18/03/2025; PwC e EY, mar/2025",tag:"Big Four"},
 {d:"Mai 2025",s:"AWS Transform",t:"Modernização agêntica chega ao mercado",x:"AWS Transform (mainframe, VMware, .NET) em disponibilidade geral. Hoje: migração sem custo e US$ 0,035 por minuto de agente em transformações customizadas.",src:"SiliconANGLE 15/05/2025; preços set/2026",tag:"Hyperscaler"},
 {d:"Jun 2025",s:"KPMG Workbench",t:"KPMG Workbench: plataforma multiagente",x:"Base das plataformas de entrega Velocity (Advisory), Digital Gateway (Tax) e Clara (auditoria).",src:"KPMG International, 17/06/2025",tag:"Big Four"},
 {d:"Jan 2026",s:"McKinsey 25k",t:"McKinsey: 25 mil agentes e honorários por resultado",x:"~25 mil agentes ao lado de ~40 mil pessoas; ~25% dos honorários globais atrelados a resultado (nov/2025).",src:"BI/HBR jan/2026; Yahoo/BI nov/2025",tag:"Estratégia"},
 {d:"Mai 2026",s:"A&M AI Board",t:"A&M cria o Global AI Board",x:"Meta de <b>50% da receita ligada a IA até 2028</b> (até US$ 3,5 bi) e até 200 contratações. Ferramentas: A&M Assist e DiligenceGPT.",src:"A&M press release 05/05/2026; Bloomberg 04/05/2026",tag:"A&M"},
 {d:"Jun 2026",s:"PwC × ToltIQ",t:"Due diligence com IA vira disputa por exclusividade",x:"PwC passa a ser a única firma de serviços profissionais da ToltIQ; já havia lançado ‘Harvey, powered by PwC’ para deals.",src:"PwC US, jun/2026; PwC Global, jul/2025",tag:"M&A"},
 {d:"Jul 2026",s:"Ode · Bain",t:"Laboratórios de IA entram no canal de PE",x:"Ode with Anthropic (Blackstone, H&F) leva engenheiros às investidas; Bain replica o software do alvo com Claude Code na DD.",src:"BusinessWire jul/2026; FT jul/2026",tag:"PE"},
 {d:"Ago 2026",s:"AlixPartners",t:"AlixPartners compra a Artium (engenharia agêntica)",x:"O par mais comparável à A&M compra capacidade de IA pronta: 80+ pessoas, parceira de OpenAI e Anthropic.",src:"AlixPartners, 04/08/2026",tag:"Par direto"},
 {d:"Set 2026",s:"Falconi · CI&T",t:"Consultorias brasileiras viram ‘AI-native’",x:"Falconi investe R$ 100 mi em IA (80% dos projetos com agentes); CI&T monetiza IA pela plataforma Flow.",src:"Jornal do Comércio set/2026; IT Forum 2026",tag:"Brasil"}
];

/* ---------- TIMELINE · 2026, IA nas consultorias (benchmark) ---------- */
const TL_2026=[
 {d:"Jan 2026",s:"McKinsey",t:"McKinsey opera com 25 mil agentes de IA",x:"Cerca de 25 mil agentes trabalham ao lado de ~40 mil pessoas; perto de 25% dos honorários globais já são cobrados por resultado.",src:"Business Insider / HBR, jan/2026; Yahoo Finance, nov/2025",tag:"Estratégia"},
 {d:"Fev 2026",s:"Frontier Alliance",t:"OpenAI reúne McKinsey, BCG, Accenture e Capgemini",x:"Aliança para levar agentes a clientes: estratégia desenha o modelo operacional, integradores implementam.",src:"Fortune, 23/02/2026",tag:"Ecossistema"},
 {d:"Mai 2026",s:"A&M AI Board",t:"Alvarez & Marsal cria o Global AI Board",x:"A firma global anuncia o conselho de IA e, segundo a Bloomberg, mira 50% da receita vinda de trabalho com IA até 2028, com até 200 contratações. Já usa A&M Assist e DiligenceGPT.",src:"A&M press release, 05/05/2026; Bloomberg, 04/05/2026",tag:"Alvarez & Marsal"},
 {d:"Jun 2026",s:"PwC × ToltIQ",t:"Due diligence com IA vira disputa por exclusividade",x:"PwC passa a ser a única firma de serviços profissionais da ToltIQ, plataforma de diligência com IA; já vendia a clientes a ‘Harvey, powered by PwC’.",src:"PwC US, jun/2026; PwC Global, jul/2025",tag:"M&A"},
 {d:"Jul 2026",s:"Ode · Bain",t:"Laboratórios de IA entram no canal de private equity",x:"Ode with Anthropic (Blackstone, Hellman & Friedman) coloca engenheiros dentro das investidas; a Bain replica o software do alvo com Claude Code durante a diligência.",src:"BusinessWire, jul/2026; Financial Times, jul/2026",tag:"Private equity"},
 {d:"Ago 2026",s:"AlixPartners",t:"AlixPartners compra a Artium",x:"O par mais comparável à A&M adquire uma consultoria de engenharia agêntica com mais de 80 pessoas, parceira de OpenAI e Anthropic.",src:"AlixPartners, 04/08/2026",tag:"Par direto"},
 {d:"Set 2026",s:"Falconi · CI&T",t:"Consultorias brasileiras viram ‘AI-native’",x:"Falconi investe R$ 100 milhões em IA, com 80% dos projetos usando agentes; a CI&T monetiza IA pela plataforma Flow.",src:"Jornal do Comércio, set/2026; IT Forum, 2026",tag:"Brasil"}
];

/* ---------- NOMENCLATURA · possível configuração ---------- */
const NM_MARKET=[["Technology Strategy & Transformation · CIO Advisory","IT Advisory · Strategy, Leadership & Value",null],["Office of the CIO · IT Finance · TBM","Tech Spend Optimization & Spend Radar","1.5"],["Tech Due Diligence · Transaction Technology","AI-Powered Tech Due Diligence","3.1"],["Separation & Carve-out · TSA · Dia 1","Integration & Separation Blueprint","3.2"],["Trusted AI · Trustworthy AI · AI governance","AI Value & Governance Office","1.7"],["LegacyX · GenWizard · AWS Transform","Legacy X-Ray & AI Modernization","4.6"]];
const NM_PRODS=[["Tech Maturity & Value Assessment","1.1"],["Digital Strategy & Roadmapping","1.2"],["Interim CIO / CTO Leadership + Embedded Tech Leadership + C-Level Tech Enablement","1.3"],["Strategic Tech Tax + Innovation Tax Incentives","1.6"],["ERP Readiness & Gap Analysis","2.2"],["TMO + Modelo de Implantação e Governança","2.3"],["IT Due Diligence (Buy Side) + (Sell Side)","3.1"],["IT Integration Management Office + IT Separation Management Office","3.3"],["Strategy Architecture","4.1"],["Strategy Application","4.2"],["Infrastructure Management","4.3"],["Complex Migrations Support","4.4"]];

/* ---------- ROADMAP de lançamento (closing) ---------- */
const TL_LAUNCH=[
 {d:"4T 2026",s:"Onda 0 · Fundação",t:"Fábrica de produtos e quick wins",x:"Nomear donos de produto, padronizar fichas, ativar o LLM corporativo seguro. Lançar <b>ERP & Tax Reform Readiness</b> (janela da CBS em 01/01/2027) e <b>Tech Spend Optimization & Spend Radar</b> (orçamento 2027).",tag:"0–90 dias"},
 {d:"1T 2027",s:"Onda 1 · Signature",t:"Produtos A&M Signature com IA",x:"<b>AI-Powered Tech Due Diligence</b> (3 níveis), <b>Tech Project Rescue</b> com kit forense, <b>Interim & Embedded Tech Leadership</b> com bancada e copiloto.",tag:"Proteger o núcleo"},
 {d:"2T 2027",s:"Onda 2 · Novos IA",t:"Primeiros produtos novos",x:"<b>AI Value & Governance Office</b> (assinatura), <b>AI-Native IT Productivity</b> (piloto de 10 semanas) e <b>Legacy X-Ray & AI Modernization</b>, com 3–5 clientes-piloto cada e preço de lançamento.",tag:"Criar com IA"},
 {d:"3T 2027",s:"Onda 3 · Recorrência",t:"Plataformas e assinaturas",x:"<b>PE Tech Value Radar</b> com 1–2 fundos-âncora; <b>Spend Radar</b> como assinatura; benchmark DTS Brasil como ativo de dados.",tag:"Receita recorrente"},
 {d:"4T 2027",s:"Revisão",t:"Revisão do portfólio",x:"O comitê trimestral acompanha receita por produto, margem, recorrência e conversão; a revisão anual decide escalar, ajustar ou aposentar.",tag:"Ciclo anual"}
];
