/* =====================================================================
   SLIDES · conteúdo renderizado e ganchos de entrada
   ===================================================================== */
const ONEPAGE=slides.findIndex(s=>s.dataset.t==="One-page · novo portfólio")+1;
const PBY=c=>PRODUCTS.find(p=>p.code===c);
const plink=(c,cls)=>{const p=PBY(c);return p?`<a href="#p=${p.id}" data-pd="${p.id}" class="plink ${cls||""} ${p.st}" title="Abrir ficha: ${p.name}">${p.code} ${p.name}</a>`:""};
const strip=h=>h.replace(/<[^>]+>/g,"");
const ICO={spark:'<path d="M12 2l1.9 6.1L20 10l-6.1 1.9L12 18l-1.9-6.1L4 10l6.1-1.9z"/>',doc:'<path d="M6 3h9l4 4v14H6z"/><path d="M15 3v4h4M9 12h7M9 16h7"/>',deal:'<path d="M3 12l4-4 4 3 3-3 7 6"/><path d="M3 18h18"/>',coin:'<circle cx="12" cy="12" r="8"/><path d="M14.5 9.5c-.6-.9-1.5-1.2-2.5-1.2-1.4 0-2.5.7-2.5 1.9 0 2.8 5 1.5 5 4.2 0 1.2-1.1 2-2.5 2-1.1 0-2.1-.4-2.7-1.3M12 6.5v1.8M12 16.4v1.6"/>',shield:'<path d="M12 3l8 3v6c0 4.5-3.4 8.2-8 9-4.6-.8-8-4.5-8-9V6z"/><path d="M9 12l2 2 4-4"/>',people:'<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3 20c0-3.3 2.7-6 6-6s6 2.7 6 6"/><path d="M15 14.5c3 0 6 2 6 5.5"/>'};
const ico=(k,c)=>`<svg class="i24" viewBox="0 0 24 24" style="color:${c||"#fff"}">${ICO[k]}</svg>`;

/* ---------- morph scene (capa e capas de pilar) ---------- */
function MorphScene(svg,cfg){const W=640,cx=320,cy=300,R=170;svg.innerHTML="";const id="g"+Math.random().toString(36).slice(2,7);
  const df=S("defs",null,svg),lg=S("linearGradient",{id,x1:0,y1:0,x2:1,y2:1},df);S("stop",{offset:0,"stop-color":"#5E8AB4"},lg);S("stop",{offset:.6,"stop-color":"#1F3263"},lg);S("stop",{offset:1,"stop-color":"#0E1C39"},lg);
  const rg=S("radialGradient",{id:id+"r"},df);S("stop",{offset:0,"stop-color":"rgba(247,140,22,.35)"},rg);S("stop",{offset:1,"stop-color":"rgba(247,140,22,0)"},rg);
  S("circle",{cx,cy,r:285,fill:`url(#${id}r)`,opacity:.55},svg);
  S("circle",{cx,cy,r:250,fill:"none",stroke:"rgba(255,255,255,.08)","stroke-width":1,"stroke-dasharray":"2 7"},svg);
  const outer=S("path",{fill:`url(#${id})`,stroke:"rgba(157,187,217,.65)","stroke-width":2,opacity:.95},svg);
  const inner=S("path",{fill:"none",stroke:"rgba(247,140,22,.75)","stroke-width":2,"stroke-dasharray":"5 6"},svg);
  const mx=Math.max(...cfg.states.map(s=>s.dots));const dots=[];for(let k=0;k<mx;k++){const c=S("circle",{cx:0,cy:0,r:7,fill:"#9DBBD9"},svg);c.style.transition="transform 1.1s cubic-bezier(.65,0,.35,1),fill .6s,opacity .6s";dots.push(c)}
  const g=S("g",{style:"transition:opacity .35s"},svg);const t1=T(g,cx,cy-6,"",{"text-anchor":"middle",fill:"#fff",style:"font:700 76px var(--fh)"});const t2=T(g,cx,cy+30,"",{"text-anchor":"middle",fill:"#F9A64A",style:"font:800 13px var(--fb);letter-spacing:.2em"});const t3=T(g,cx,cy+52,"",{"text-anchor":"middle",fill:"#C8DBEB",style:"font:500 13px var(--fb)"});
  const rnd=k=>{const a=Math.sin(k*12.9898)*43758.5453;return a-Math.floor(a)};
  const shapes=cfg.states.map(s=>({pts:s.shape==="blob"?SHAPES.blob(cx,cy,R,.6):s.shape==="hex"?SHAPES.hex(cx,cy,R*1.08):s.shape==="square"?SHAPES.square(cx,cy,R*1.75,26):SHAPES.circle(cx,cy,R)}));
  const innerPts=cfg.states.map(s=>s.shape==="blob"?SHAPES.blob(cx,cy,R*.72,2.2):s.shape==="hex"?SHAPES.hex(cx,cy,R*.74):s.shape==="square"?SHAPES.square(cx,cy,R*1.2,18):SHAPES.circle(cx,cy,R*.74));
  const btns=cfg.btnHost?cfg.states.map((s,k)=>{const b=H("button",{class:"pill",style:"border:1px solid rgba(255,255,255,.25);background:rgba(255,255,255,.08);color:#C8DBEB;padding:8px 14px;font:700 11px var(--fb);letter-spacing:.08em;text-transform:uppercase;transition:background .3s,color .3s"},cfg.btnHost,s.btn);b.onclick=()=>mp.go(k,true);return b}):[];
  function place(k){const st=cfg.states[k];dots.forEach((d,j)=>{let x,y,op=1,fill="#9DBBD9";if(j>=st.dots){op=0;x=cx;y=cy}else if(st.shape==="blob"){const a=rnd(j+1)*Math.PI*2,rr=205+rnd(j+7)*70;x=cx+rr*Math.cos(a);y=cy+rr*Math.sin(a);fill="#6E8FBF"}else{const a=-Math.PI/2+j*2*Math.PI/st.dots;x=cx+245*Math.cos(a);y=cy+245*Math.sin(a);fill=st.ai&&j<st.ai?"#F78C16":"#fff";if(st.ai&&j>=st.ai)fill="#9DBBD9"}
      d.style.transform=`translate(${x}px,${y}px)`;d.style.opacity=op;d.setAttribute("fill",fill)});
    g.style.opacity=0;setTimeout(()=>{t1.textContent=st.big;t2.textContent=st.lab;t3.textContent=st.sub||"";g.style.opacity=1},350);
    btns.forEach((b,j)=>{b.style.background=j===k?"#F78C16":"rgba(255,255,255,.08)";b.style.color=j===k?"#0E1C39":"#C8DBEB"})}
  const mp=Morpher({path:outer,states:shapes,dwell:cfg.dwell||2400,onState:(k)=>{place(k);morphTo(inner,readPts(inner),innerPts[k],1150)}});
  function readPts(p){const d=p.getAttribute("d");if(!d)return innerPts[0];return d.slice(1,-1).split("L").map(s=>s.split(" ").map(Number))}
  inner.setAttribute("d",toD(innerPts[0]));place(0);return mp}

/* ---------- capa ---------- */
$("cvLogos").innerHTML=`${amLogo(42)}<span class="am-div" style="height:48px;background:rgba(255,255,255,.3)"></span>${dtsLogo(44)}`;
$("cvLines").innerHTML=amLines(760,450,1);
const cvMorph=MorphScene($("cvMorph"),{btnHost:$("cvStates"),states:[
  {shape:"blob",big:"29",lab:"SERVIÇOS",sub:"sob medida · sobrepostos · sem IA",dots:29,btn:"Serviço"},
  {shape:"hex",big:"24",lab:"PRODUTOS",sub:"escopo · método · ferramenta · preço",dots:24,btn:"Produto"},
  {shape:"circle",big:"19",lab:"COM IA NO NÚCLEO",sub:"plataforma DTS · dados · recorrência",dots:24,ai:19,btn:"Plataforma"}]});
ENTER["Capa"]=()=>cvMorph.play();

/* ---------- resumo ---------- */
(function(){const M=[["O que temos","29","serviços em 4 pilares, com sobreposições, nomes pouco claros e IA ausente","#122143",6],["O que mudar","13 → 6","serviços que se sobrepõem fundidos em 6 produtos; nomes alinhados ao mercado","#33556D",6],["O que retirar","2","IT Business Partner e IT M&amp;A Playbook deixam de ser vendidos isolados","#BC0404",6],["Melhorar com IA","15","produtos remodelados com IA no método; IA presente em todos os 24","#5E8AB4",3],["Criar com IA","4","AI Value &amp; Governance Office · AI-Native IT · PE Tech Value Radar · Legacy X-Ray","#F78C16",3]];
  M.forEach(([k,v,d,c,go],i)=>{const b=H("button",{class:"card clk"+(i===4?" holo":""),"data-a":"stack","data-go":go,style:`--d:${4+i};--r:${(i-2)*2}deg;--sx:${(2-i)*30}px;text-align:left;border-top:5px solid ${c};padding:12px 14px`,title:"Ir para o detalhe"},$("moves"));
    b.innerHTML=`<div class="eye" style="color:${c};margin-bottom:2px">${k}</div><div class="big" style="font-size:44px;color:${i===4?"#C96A05":"#002B49"}">${v}</div><p style="font-size:12px;margin-top:4px">${d}</p>`});
  [["01/01/2027","CBS plena: ERP e fiscal precisam estar prontos","LC 214/2025"],["2027","fim da manutenção padrão do SAP ECC (extensível a 2030)","Baguete"],["50%","dos deals no Brasil com PE/VC em 2025","KPMG"],["50% até 2028","meta global A&amp;M de receita ligada a IA","Bloomberg"]].forEach(([v,l,s])=>{const d=H("div",{class:"kpi-t",style:"padding:10px 12px"},$("whyNow"));d.innerHTML=`<div class="v" style="font-size:26px">${v}</div><div class="l" style="font-size:11.5px">${l}</div><div class="s"><span class="ev">E · ${s}</span></div>`});
  const sig=PRODUCTS.filter(p=>p.sig),nw=PRODUCTS.filter(p=>p.st==="new");
  $("bets").innerHTML=`<div><div class="eye" style="color:#9DBBD9;margin-bottom:4px">★ A&amp;M Signature · proteger e escalar</div><div class="chips-row">${sig.map(p=>plink(p.code,"dk")).join("")}</div></div><div><div class="eye" style="color:var(--orange-l);margin-bottom:4px">Novos com IA · incubar e lançar</div><div class="chips-row">${nw.map(p=>plink(p.code,"new")).join("")}</div></div>`;
  const parts=[["Abertura","Mercado, benchmark, raio-X",4],["Pilar 1","IT Advisory",8],["Pilar 2","Technology Transformation",12],["Pilar 3","Tech M&amp;A",16],["Pilar 4","Modernization",20],["Fechamento","Fábrica, roadmap, decisões",24]];
  parts.forEach(([a,b,go])=>{const x=H("button",{class:"clk","data-go":go,style:"text-align:left;border:1px solid var(--line);border-left:4px solid var(--orange);border-radius:8px;background:#fff;padding:6px 10px"},$("agenda"));x.innerHTML=`<div style="font:800 13px var(--fh);color:var(--navy);text-transform:uppercase;letter-spacing:.03em">${a}</div><div class="small" style="font-size:10.5px">${b}</div>`})})();

/* ---------- one-page + spotlight ---------- */
(function(){const g=$("opGrid");PILLARS.forEach(pl=>{const col=H("div",{class:"op-col",id:"opc"+pl.n,"data-a":"up",style:`--d:${3+pl.n}`},g);
  col.innerHTML=`<div class="op-hd"><div class="n">PILAR ${pl.n}</div><h3>${pl.name}</h3><p>${pl.short}</p><span class="cnt">${pl.was} → ${pl.now}</span></div>`;
  const list=H("div",{class:"op-list"},col);PRODUCTS.filter(p=>p.pillar===pl.n).forEach((p,k)=>{const a=H("a",{href:"#p="+p.id,"data-pd":p.id,class:`prod ${p.st}${p.st==="new"?" holo":""}`,title:"Abrir ficha: "+p.name,style:`--hd:${(k*.6).toFixed(1)}s`},list);
    a.innerHTML=`<span class="bar"></span><span style="min-width:0"><span class="nm">${p.code} · ${p.name}${p.sig?'<span class="sig">★ SIGNATURE</span>':""}</span><span class="ds">${p.tagline}</span></span><span class="go">›</span>`})});
  const st=PILLARS.map(pl=>{const ps=PRODUCTS.filter(p=>p.pillar===pl.n),nw=ps.filter(p=>p.st==="new").map(p=>p.name),sg=ps.filter(p=>p.sig).map(p=>p.name);
    return{sel:"#opc"+pl.n,btn:"P"+pl.n,title:`Pilar ${pl.n} · ${pl.name}`,text:`${pl.was} serviços → ${pl.now} produtos.${sg.length?` <b>Signature:</b> ${sg.join(", ")}.`:""} <b>Novo:</b> ${nw.join(", ")}.`}});
  st.push({sel:"#opAI",btn:"Plataforma",title:"Plataforma DTS de IA & dados",text:"Ativos compartilhados por todos os produtos: diagnóstico, radar de gastos, benchmark, agentes e LLM seguro. É o que torna o serviço replicável.",capY:330});
  const sp=Spotlight($("opHost"),st,$("opSeg"));segSync($("opSeg"));
  ENTER["One-page · novo portfólio"]=()=>{sp.set(-1);segSync($("opSeg"))};
  STEP["One-page · novo portfólio"]=d=>{if(d>0){if(sp.cur<st.length-1){sp.set(sp.cur+1);return true}sp.set(-1);return false}if(sp.cur>=0){sp.set(sp.cur-1);return true}return false}})();

/* ---------- forças de mercado ---------- */
(function(){[["US$ 67,8 bi","mercado de TI no Brasil em 2025 (+18,5%); 10º do mundo","ABES/IDC mar/2026"],["US$ 3,4 bi","gasto com IA no Brasil em 2026 (+30%)","IDC 2026"],["1.581","transações de M&amp;A em 2025; 50% com PE/VC","KPMG mar/2026"],["17%","das empresas (10+ empregados) usam IA; 50% das grandes","Cetic.br 2025"]].forEach(([v,l,s],i)=>{const d=H("div",{class:"kpi-t","data-a":"up",style:`--d:${2+i};border-top:4px solid ${i%2?"#5E8AB4":"#122143"}`},$("mktKpis"));d.innerHTML=`<div class="v">${v}</div><div class="l">${l}</div><div class="s"><span class="ev">E · ${s}</span></div>`});
  const F=[["spark","IA: uso amplo, escala rara","56% dos CEOs ainda sem retorno financeiro com IA; só ~25% das empresas escalam ≥40% dos pilotos.","56%","sem retorno com IA","PwC · Deloitte 2026",["1.7","2.6","1.2"]],
   ["doc","Reforma Tributária + SAP ECC","CBS plena em 01/01/2027, dois regimes até 2033 e fim da manutenção padrão do ECC em 2027.","01/01/27","CBS plena","LC 214/2025 · Baguete",["2.2","2.4","2.3"]],
   ["deal","Deals com private equity","PE/VC em metade dos deals; TI é o setor nº 1 (274 deals no 1S26); separações como a da Raízen até 2027.","50%","dos deals com PE/VC","KPMG 2025 · 1S26",["3.1","3.5","3.2"]],
   ["coin","Custo de tecnologia sob escrutínio","TI cresce só 5,3% em 2026; VMware 8–15× mais caro; até 40% dos insumos de TI são importados.","+5,3%","crescimento de TI em 2026","ABES/IDC · Baguete · TI Inside",["1.5","4.3","4.2"]],
   ["shield","Risco e regulação","Ataques à cadeia do Pix; CMN 5.274; marco de IA (PL 2338) para depois das eleições; ANPD virou agência.","R$ 800 mi","desviados no ataque à C&M","Finsiders · Legisweb · MobileTime",["4.5","1.7"]],
   ["people","Talento e liderança","Metade das empresas sem talento para IA; M&A e reestruturações pedem liderança de tecnologia imediata.","53%","sem talento necessário para IA","KPMG Global Tech Report",["1.3","1.4","2.5"]]];
  F.forEach(([ic,t,x,v,vl,src,ps],i)=>{const d=H("div",{class:"force","data-a":"up",style:`--d:${5+i}`},$("forces"));d.innerHTML=`<div class="ic">${ico(ic)}</div><div><h4>${t}</h4><p>${x}</p><div class="v">${v}<small>${vl}</small></div><div style="margin-top:4px"><span class="ev">E · ${src}</span></div><div class="fx-imp"><span class="hy">Implicação</span> ${ps.map(c=>plink(c,"sm")).join(" ")}</div></div>`})})();

/* ---------- benchmark · timeline ---------- */
(function(){const host=$("tlMarket");let tl=null;
  const T4=[["Plataforma própria + agentes","Zora AI, agent OS, EY.ai, Workbench e Lilli, com NVIDIA, Microsoft, Google e laboratórios de IA.","E","A&amp;M não deve competir em plataforma: deve ser neutra e orquestradora."],["Preço por resultado e por ativo","McKinsey ~25% outcome-based; Deloitte vende agentes por assinatura; IBM ‘asset-based consulting’.","E","O DNA A&amp;M de honorário por resultado vira vantagem."],["Nomes de mercado consolidados","Technology Strategy & Transformation, CIO Advisory, Office of the CIO, Separation & Carve-out, Trusted AI.","E","Nomes DTS em inglês e alinhados ao mercado facilitam RFP e compras."],["White space do operador","CIO interino não encontrado nas Big Four; AlixPartners compra capacidade (Artium); A&M já tem A&M Assist e DiligenceGPT.","E","Produtizar o DNA de operador com IA, antes dos pares."]];
  T4.forEach(([t,x,e,h],i)=>{const d=H("div",{class:"card","data-a":"up",style:`--d:${8+i};padding:10px 14px;border-top:4px solid ${i===3?"#F78C16":"#33556D"}`},$("benchTake"));d.innerHTML=`<h4>${t}</h4><p style="font-size:11.8px">${x} <span class="ev">E</span></p><p style="font-size:11.8px;margin-top:5px;color:#002B49"><b>→</b> ${h} <span class="hy">H</span></p>`});
  [["Technology Strategy & Transformation · CIO Advisory","IT Advisory · Strategy, Leadership & Value",null],["Office of the CIO · IT Finance · TBM","Tech Spend Optimization & Spend Radar","1.5"],["Tech Due Diligence · Transaction Technology","AI-Powered Tech Due Diligence","3.1"],["Separation & Carve-out · TSA · Dia 1","Integration & Separation Blueprint","3.2"],["Trusted AI · Trustworthy AI · AI governance","AI Value & Governance Office","1.7"],["LegacyX · GenWizard · AWS Transform","Legacy X-Ray & AI Modernization","4.6"]].forEach(([m,d,c],i)=>{const el=H(c?"a":"div",{class:"nm-i","data-a":"up",style:`--d:${13+i}`},$("nmRow"));if(c){el.href="#p="+PBY(c).id;el.dataset.pd=PBY(c).id}el.innerHTML=`<div class="m">${m}</div><div class="ar">→ DTS</div><div class="d">${c?c+" · ":""}${d}</div>`});
  ENTER["Benchmark · IA nas consultorias"]=()=>{if(!tl)tl=Timeline(host,TL_MARKET,{w:1508,y:232,cardY:44,x0:70,x1:1440,dwell:2300});tl.play()};
  $("tlPlay").onclick=()=>tl&&tl.play();PRINT.push(()=>{if(!tl)tl=Timeline(host,TL_MARKET,{w:1508,y:232,cardY:44,x0:70,x1:1440,dwell:2300});tl.stopAuto();tl.set(TL_MARKET.length-1)})})();

/* ---------- raio-X ---------- */
(function(){const svg=$("rxChart"),L=70,Rr=910,Tp=16,B=556,x=v=>L+(v-1.8)/(5-1.8)*(Rr-L),y=v=>B-(v-1.8)/(5-1.8)*(B-Tp);const mid=3.3;
  const q=[[x(mid),Tp,Rr-x(mid),y(mid)-Tp,"#FEF1E2","ESCALAR · NÚCLEO A&M",Rr-12,Tp+20,"end"],[L,Tp,x(mid)-L,y(mid)-Tp,"#EEF3F8","DEFENDER E PRODUTIZAR",L+12,Tp+20,"start"],[x(mid),y(mid),Rr-x(mid),B-y(mid),"#EEF3F8","DIFERENCIAR COM IA OU PARCERIA",Rr-12,B-12,"end"],[L,y(mid),x(mid)-L,B-y(mid),"#F4F5F7","CONSOLIDAR OU RETIRAR",L+12,B-12,"start"]];
  q.forEach(([a,b,w,h,f,t,tx,ty,an])=>{S("rect",{x:a,y:b,width:w,height:h,fill:f},svg);T(svg,tx,ty,t,{"text-anchor":an,fill:"#6B7B8C",style:"font:800 11px var(--fb);letter-spacing:.12em"})});
  S("line",{x1:L,y1:B,x2:Rr,y2:B,stroke:"#98A6B3","stroke-width":1.5},svg);S("line",{x1:L,y1:Tp,x2:L,y2:B,stroke:"#98A6B3","stroke-width":1.5},svg);
  for(let v=2;v<=5;v++){T(svg,x(v),B+18,String(v),{"text-anchor":"middle",fill:"#98A6B3",style:"font:600 11px var(--fb)"});T(svg,L-10,y(v)+4,String(v),{"text-anchor":"end",fill:"#98A6B3",style:"font:600 11px var(--fb)"})}
  T(svg,(L+Rr)/2,B+42,"ATRATIVIDADE DE MERCADO · BRASIL 2026–27 →",{"text-anchor":"middle",fill:"#002B49",style:"font:800 11.5px var(--fb);letter-spacing:.12em"});
  const yl=T(svg,22,(Tp+B)/2,"DIREITO DE VENCER · A&M →",{"text-anchor":"middle",fill:"#002B49",style:"font:800 11.5px var(--fb);letter-spacing:.12em"});yl.setAttribute("transform",`rotate(-90 22 ${(Tp+B)/2})`);
  const DC={keep:["#33556D","#33556D","#fff"],ai:["#5E8AB4","#5E8AB4","#fff"],merge:["#fff","#8FA6BA","#35516A"],cut:["#fff","#BC0404","#BC0404"]};const DN={keep:"Manter",ai:"Aprimorar com IA",merge:"Fundir",cut:"Retirar"};
  const nodes=[];NEWPOS.forEach(n=>{const p=PBY(n.c),gg=S("g",{class:"bubble","data-p":p.pillar},svg);S("circle",{cx:x(n.x),cy:y(n.y),r:19,fill:"rgba(247,140,22,.12)",stroke:"#F78C16","stroke-width":2,"stroke-dasharray":"4 3"},gg);T(gg,x(n.x),y(n.y)+4,n.c,{"text-anchor":"middle",fill:"#B35F00",style:"font:800 11px var(--fb)"});tip(gg,`★ Novo · ${p.code} ${p.name}`,strip(p.tagline));gg.style.cursor="pointer";gg.addEventListener("click",()=>openPD(p.id));nodes.push(gg)});
  OLD.forEach(o=>{const [f,s,tc]=DC[o.d],gg=S("g",{class:"bubble","data-p":o.p,"data-a":"pop",style:`--d:${2+(o.p-1)*2}`},svg);S("circle",{cx:x(o.x),cy:y(o.y),r:17,fill:f,stroke:s,"stroke-width":o.d==="merge"?2:2.2,"stroke-dasharray":o.d==="merge"?"4 3":"none"},gg);T(gg,x(o.x),y(o.y)+4,o.id.toUpperCase(),{"text-anchor":"middle",fill:tc,style:"font:800 10.5px var(--fb)"});
    const dest=PBY(o.to);tip(gg,`${o.id.toUpperCase()} · ${o.n}`,`${DN[o.d]} → ${dest.code} ${dest.name}. ${o.w}`);gg.style.cursor="pointer";gg.addEventListener("click",()=>openPD(dest.id));nodes.push(gg)});
  const list=$("rxList");PILLARS.forEach(pl=>{H("div",{class:"xg",style:"padding:6px 0 3px;font:800 10.5px var(--fb);letter-spacing:.12em;color:#5E8AB4;text-transform:uppercase"},list,`Pilar ${pl.n} · ${pl.name}`);
    OLD.filter(o=>o.p===pl.n).forEach(o=>{const dest=PBY(o.to);const r=H("div",{class:"rx-row","data-p":pl.n},list);r.innerHTML=`<b>${o.id.toUpperCase()}</b><span class="nm" title="${o.n}">${o.n}</span><span class="st ${o.d}" style="font-size:8.5px;padding:3px 6px">${DN[o.d]}</span><a href="#p=${dest.id}" data-pd="${dest.id}" class="to">→ ${dest.code}</a>`;tip(r,o.n,o.w)})});
  const seg=$("rxSeg");["Todos","P1","P2","P3","P4"].forEach((t,k)=>{const b=H("button",{class:k?"":"on"},seg,t);b.onclick=()=>{seg.querySelectorAll("button").forEach(x=>x.classList.toggle("on",x===b));segSync(seg);nodes.forEach(n=>n.style.opacity=!k||+n.dataset.p===k?1:.12);list.querySelectorAll(".rx-row").forEach(r=>r.style.opacity=!k||+r.dataset.p===k?1:.3)}});
  ENTER["Raio-X do portfólio atual"]=()=>segSync(seg)})();

/* ---------- três caminhos ---------- */
(function(){const P=[["Incremental","IA dentro dos serviços de hoje","Mantém os 29 serviços e nomes; IA como produtividade interna da equipe.",["Rápido e barato","Não resolve sobreposições nem nomes","Preço continua por hora: pressão de preço com a IA","<b>Receita:</b> horas e projetos sob medida"],[1,1,0],"~3 meses",false],
  ["Transformacional","Portfólio de produtos com IA","29 → 24 produtos com escopo, método, ferramenta, dados e preço; 4 Signature; 4 novos com IA.",["Funde 13 serviços sobrepostos em 6 produtos","IA no método de 19 produtos","Plataforma DTS compartilhada","<b>Receita:</b> sprint fixo + execução com êxito + primeiras assinaturas"],[3,4,2],"6–9 meses",true],
  ["Disruptivo","DTS como plataforma (service-as-software)","Radares e escritórios por assinatura, benchmark Brasil como produto de dados e agentes operando para o cliente.",["Receita recorrente e escalável","Exige engenharia, dados e parcerias (como AlixPartners–Artium)","Risco de canibalizar projetos","<b>Receita:</b> assinatura por empresa, agente ou fundo"],[5,5,5],"18–24 meses",false]];
  P.forEach(([k,h,p,li,m,t,rec],i)=>{const d=H("div",{class:"path3"+(rec?" rec":""),"data-a":"up",style:`--d:${4+i*2}`},$("paths"));
    const mt=(lab,v,o)=>`<div style="display:grid;grid-template-columns:110px 1fr;gap:8px;align-items:center;margin-top:5px"><span class="small" style="font-size:11px;font-weight:700;color:#35516A">${lab}</span><div class="meter${o?" o":""}">${[1,2,3,4,5].map(j=>`<i class="${j<=v?"on":""}"></i>`).join("")}</div></div>`;
    d.innerHTML=`${rec?'<span class="rib">★ RECOMENDADO</span>':""}<div class="k">${k}</div><h3 style="margin-top:4px">${h}</h3><p style="margin-top:8px">${p}</p><ul>${li.map(x=>`<li>${x}</li>`).join("")}</ul><div style="margin-top:auto;padding-top:10px;border-top:1px solid var(--line2)">${mt("Investimento",m[0])}${mt("Diferenciação",m[1],1)}${mt("Recorrência",m[2],1)}<div class="small" style="margin-top:6px;font-size:11.5px">Tempo até impacto: <b style="color:#002B49">${t}</b> <span class="hy">H</span></div></div>${rec?`<div style="margin-top:10px;background:var(--orange-bg);border:1px dashed var(--orange-line);border-radius:8px;padding:7px 10px;font:600 11.8px/1.4 var(--fb);color:#8A4A05">+ incubar 2 apostas disruptivas: ${plink("3.5")} e ${plink("1.7")}</div>`:""}`})})();

/* ---------- capas de pilar ---------- */
const PCM={};
document.querySelectorAll(".pcover").forEach(sec=>{const n=+sec.dataset.pillar,pl=PILLARS[n-1],ps=PRODUCTS.filter(p=>p.pillar===n),k=ps.filter(p=>p.st!=="keep").length,nw=ps.filter(p=>p.st==="new"),sg=ps.filter(p=>p.sig);
  sec.innerHTML=`<div class="pillar-n">0${n}</div><div class="pc-lines">${amLines(640,380,1)}</div>
  <div style="position:absolute;left:84px;top:62px;right:760px;z-index:2">
    <div class="cover-wm" data-a="fade">${amLogo(34)}<span class="am-div" style="height:40px;background:rgba(255,255,255,.3)"></span>${dtsLogo(36)}</div>
    <div class="eye" data-a="fade" style="--d:2;color:var(--orange);margin-top:70px;font-size:12px">Pilar 0${n} · ${pl.short}</div>
    <h1 class="cv-title kin" style="font-size:${pl.name.length>18?78:96}px">${pl.name}</h1>
    ${pl.to!==pl.name?`<div data-a="fade" style="--d:5;margin-top:12px;font:600 14px var(--fb);color:#9DB7CE">Nome proposto: <b style="color:#fff">${pl.to}</b></div>`:""}
    <p class="cv-lead" data-a="blur" style="--d:6;margin-top:18px;font-size:19px">${pl.def}</p>
    <div data-a="up" style="--d:8;display:flex;gap:40px;margin-top:28px">
      <div><div class="big" style="color:#fff;font-size:50px">${pl.was} → ${pl.now}</div><div class="small" style="color:#9DB7CE;font-size:12px">serviços → produtos</div></div>
      <div><div class="big" style="color:var(--orange-l);font-size:50px">${k}/${pl.now}</div><div class="small" style="color:#9DB7CE;font-size:12px">com IA no núcleo</div></div>
      <div><div class="big" style="color:#fff;font-size:50px">${nw.length}</div><div class="small" style="color:#9DB7CE;font-size:12px">produto novo</div></div>
    </div>
    <div data-a="fade" style="--d:10;margin-top:24px;display:flex;flex-wrap:wrap;gap:8px">${nw.map(p=>`<a href="#p=${p.id}" data-pd="${p.id}" class="pill holo" style="background:#F78C16;color:#1A1200;padding:9px 14px;font-weight:800">★ Novo · ${p.name}</a>`).join("")}${sg.map(p=>`<a href="#p=${p.id}" data-pd="${p.id}" class="pill" style="background:rgba(255,255,255,.1);color:#fff;border:1px solid rgba(255,255,255,.25);padding:9px 14px">Signature · ${p.name}</a>`).join("")}</div>
  </div>
  <svg class="pc-morph" viewBox="0 0 640 640" style="position:absolute;right:60px;top:100px;width:640px;height:640px" aria-hidden="true"></svg>
  <div class="pc-states" style="position:absolute;right:150px;bottom:60px;display:flex;gap:10px"></div>`;
  sec.querySelectorAll(".kin").forEach(kin);
  PCM[n]=MorphScene(sec.querySelector(".pc-morph"),{btnHost:sec.querySelector(".pc-states"),states:[
    {shape:"blob",big:String(pl.was),lab:"SERVIÇOS HOJE",sub:"fragmentados e sob medida",dots:pl.was,btn:"Hoje"},
    {shape:"hex",big:String(pl.now),lab:"PRODUTOS",sub:"escopo · método · preço",dots:pl.now,btn:"Produtos"},
    {shape:"circle",big:`${k}/${pl.now}`,lab:"COM IA NO NÚCLEO",sub:"IA no método, dados no centro",dots:pl.now,ai:k,btn:"Com IA"}]});
  ENTER[sec.dataset.t]=()=>PCM[n].play()});

/* ---------- personas, mercado, white space ---------- */
const PERS={1:[["CEO · Conselho","A IA está gerando resultado ou só custo? Quem lidera isso?",["1.3","1.7"]],["CFO","Quanto gastamos em tecnologia e o que dá para cortar sem risco?",["1.5","1.6"]],["CIO","Como reorganizo a área para a era dos agentes e provo valor?",["1.1","1.4"]],["Sócio de PE","Qual é a alavanca de tecnologia no EBITDA nos próximos 100 dias?",["1.3","1.5"]]],
 2:[["CFO · Head Tax","Meu ERP estará pronto para a CBS em 01/01/2027?",["2.2"]],["CIO · Compras","Qual fornecedor escolher e como contratar sem lock-in?",["2.1"]],["Sponsor · Conselho","Por que o programa atrasou e quanto custa terminar?",["2.3","2.4"]],["CHRO · CIO","Por que ninguém usa a IA que compramos?",["2.5","2.6"]]],
 3:[["Sócio de PE","Quais riscos de tecnologia mudam o preço? E depois do closing?",["3.1","3.5"]],["Corporate development","Como integramos sem parar a operação?",["3.2","3.3"]],["CFO do vendedor","Como separamos a TI e saímos da TSA no prazo?",["3.2","3.3"]],["CEO pós-deal","Onde estão as sinergias de TI prometidas no deal?",["3.4"]]],
 4:[["CIO · CTO","Por onde começo a modernizar o legado e quanto custa?",["4.1","4.6"]],["CFO","Quanto pago em virtualização, nuvem e sistemas redundantes?",["4.2","4.3"]],["CRO · COO","Aguentamos um ataque ou a falha de um terceiro?",["4.5"]],["Conselho","A migração vai dar certo? Quem garante?",["4.4"]]]};
document.querySelectorAll(".persona").forEach(h=>{PERS[h.dataset.pillar].forEach(([r,q,ps],i)=>{const d=H("div",{class:"pers"},h);d.innerHTML=`<div class="r">${r}</div><div class="q">“${q}”</div><div class="ps">${ps.map(c=>plink(c,"sm")).join(" ")}</div>`})});
const MK={1:[["Deloitte","Technology Strategy & Transformation; Technology Strategy & Architecture","Zora AI (agentes por assinatura); aliança Anthropic (470 mil profissionais); Trustworthy AI","Forte em estratégia e plataforma; CIO interino não encontrado","E"],
  ["EY","Technology Strategy & Transformation · Office of the CIO (IT Finance, Sourcing, PPM)","EY.ai Agentic Platform com NVIDIA; investimento de US$ 1,4 bi","Op model e finanças de TI robustos","E"],
  ["KPMG","CIO Advisory (TBM/Apptio); KPMG Trusted AI","Workbench multiagente; 1ª Big Four com ISO/IEC 42001","Concorrente direto em custo de TI e governança de IA","E"],
  ["PwC","Consultoria de Negócios (estratégia, digital, cloud)","agent OS; 250+ agentes com Google; AI Experience Zone em Piracicaba","Pauta via CEO Survey; IA como acelerador","E"],
  ["McKinsey · BCG · Bain","McKinsey Technology (Rewired); BCG X; Bain Vector","~25 mil agentes na McKinsey; tech e IA >40% da receita do BCG; Bain Elite Partner da OpenAI","Estratégia de IA top-down, preço premium","E"],
  ["AlixPartners","Technology Practice; CIO interino; IT cost","Comprou a Artium (engenharia agêntica, ago/2026)","Par direto no DNA de operador","E"]],
 2:[["Deloitte","Alianças de implementação (AWS até 2031; Google); Technology Center em Recife (~600 pessoas)","Zora AI integrada aos agentes SAP Joule","Escala de entrega e alianças","E"],
  ["EY","Service Delivery Center em Recife (SAP, ServiceNow, IA, RPA)","EY Beyond Tax Analytics para a Reforma","Reforma entra pelo Tax","E"],
  ["KPMG","Powered Enterprise; Consultoria Reforma Tributária","Thomson Reuters ONESOURCE; Workbench","Fiscal + tecnologia","E"],
  ["CI&T · Falconi","Entrega AI-native; hiperautomação","CI&T Flow; Falconi: R$ 100 mi em IA, 80% dos projetos com agentes","Comprimem preço de PMO e entrega","E"],
  ["TOTVS · SAP","Jornada da Reforma Tributária; RISE / S/4HANA","Chatbot especialista em Reforma (TOTVS)","O fornecedor também ‘aconselha’: falta voz independente","E"],
  ["Capgemini · Accenture · IBM","Recife com 1.000 pessoas (Capgemini); Accenture compra Tenbu","IBM Enterprise Advantage: consultoria baseada em ativos","Escala e ativos proprietários","E"]],
 3:[["Deloitte","M&A Technology: Tech DD, Software/Data Diligence, Sell-side & Exit Readiness, Separation & Carve-out (ACDC)","Plataforma de agentes Zora AI","Ciclo completo do deal","E"],
  ["EY-Parthenon","Transaction Strategy & Execution · Technology (DD, PMI, carve-out, TSA, Dia 1)","CAST Highlight reduziu >75% do tempo de avaliação de código em DD","DD + TSA + Dia 1","E"],
  ["PwC","AI technology diligence; Digital deals","‘Harvey, powered by PwC’ licenciado a clientes; exclusividade com a ToltIQ (jun/2026)","IA vendida como produto","E"],
  ["Bain","Tech Due Diligence","Replica o software do alvo com Claude Code para testar defensabilidade","DD testa o risco de disrupção por IA","E"],
  ["Entrantes","DiligenceSquared; Ode with Anthropic","DD com agentes por ~US$ 50 mil; engenheiros de IA dentro das investidas dos fundos","Pressão de preço no canal de PE","E"],
  ["A&M (hoje)","Tech & product DD, PMI, carve-out, 100 dias; PEPI","A&M Assist (abr/2025); DiligenceGPT","Ativos existem; falta produtizar no Brasil","E"]],
 4:[["McKinsey","LegacyX (QuantumBlack)","SAS → Python com squads de agentes: ~90% de precisão, cronograma −80%","Plataforma própria de modernização","E"],
  ["Accenture","GenWizard; Anthropic Business Group","Gemini para mainframe; 30 mil pessoas treinadas em Claude","Escala de fábrica","E"],
  ["IBM","watsonx Code Assistant for Z; Bob; Enterprise Advantage","~45% de ganho interno com Bob (dado do fornecedor)","Dona do mainframe","E"],
  ["AWS · Microsoft · Google","AWS Transform; GitHub Copilot app modernization; Mainframe Rewrite","Migração sem custo (AWS); até 4× mais rápido em .NET","A ferramenta vira commodity","E"],
  ["Deloitte · EY","Technology Strategy & Architecture; arquitetura corporativa","Agentes em ferramentas de EA (SAP LeanIX, Ardoq)","EA tradicional ganha automação","E"],
  ["Anthropic","Claude Code","COBOL ‘em trimestres, não anos’ (fev/2026); ação da IBM caiu no anúncio","Laboratórios vão direto ao cliente","E"]]};
const HEAT={1:["M","A","A","M","M","A"],2:["M","M","A","A","M","B"],3:["A","A","A","M","A","X"],4:["M","M","M","A","M","A"]};const HL={A:["Alta","#BC0404"],M:["Média","#F78C16"],B:["Baixa","#5E8AB4"],X:["Ativo A&amp;M","#122143"]};
document.querySelectorAll("table.mk").forEach(t=>{const n=t.dataset.mk,rows=MK[n];t.innerHTML=`<thead><tr><th style="width:140px">Firma</th><th>Como chamam a oferta</th><th>O que fazem com IA</th><th style="width:210px">Leitura para o DTS</th><th style="width:96px;text-align:center">Sobreposição <span class="hy" style="background:transparent;color:#F9A64A;border-color:#F9A64A">H</span></th></tr></thead><tbody>${rows.map((r,i)=>{const h=HL[HEAT[n][i]];return`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]} <span class="ev">E</span></td><td style="text-align:center;vertical-align:middle"><span class="heat" style="background:${h[1]}">${h[0]}</span></td></tr>`}).join("")}</tbody>`});
const WS={1:{it:[["CIO / CAIO interino","Não encontrado nas Big Four; DNA histórico da A&M.","1.3","E"],["Custo com risco compartilhado","Success fee + Spend Radar contínuo.","1.5","H"],["Valor + governança de IA","Big Four focam risco; falta quem una ROI, custo e governança com accountability.","1.7","H"],["Lei do Bem com leitura técnica por IA","Corte de 10% exige dossiê técnico melhor.","1.6","H"]],th:["Diagnósticos e estratégias são os serviços mais comoditizáveis por IA: precisam virar sprint com valor em R$.","H"]},
 2:{it:[["Independência","Sem revenda de software nem de horas de fábrica.","2.1","H"],["Lado sistêmico da Reforma","Big Four entram pelo Tax; ERP, dados e cutover ficam descobertos.","2.2","H"],["Turnaround de programas","DNA A&M; >70% dos ERPs abaixo do business case (Gartner).","2.4","E"],["Adoção medida por uso","IA comprada e não usada vira custo.","2.5","H"]],th:["Players AI-native (CI&T, Falconi) e centros de entrega no Recife comprimem o preço de PMO e implementação.","E"]},
 3:{it:[["DD + 100 dias + execução","Um contrato do signing ao Dia 100: a DD vira porta de entrada.","3.1","H"],["Assinatura do portfólio","Radar trimestral de tecnologia e IA para fundos: não encontrado no Brasil.","3.5","H"],["Ativos de IA nas TSAs","Licenças de LLM, dados e agentes compartilhados entram na separação.","3.2","H"],["Ativos A&M existentes","A&M Assist e DiligenceGPT podem ser localizados para o Brasil.","3.1","E"]],th:["DD com agentes a ~US$ 50 mil e laboratórios de IA dentro dos fundos (Ode) pressionam preço no canal de PE.","E"]},
 4:{it:[["Raio-X neutro + business case","A&M seleciona e garante; não revende ferramenta nem fábrica.","4.6","H"],["Assurance independente","O integrador não deve avaliar o próprio trabalho.","4.4","H"],["Economia de infraestrutura","VMware, nuvem e GPU com TCO e FinOps.","4.3","E"],["Resiliência pós-incidente","Cadeia do Pix e CMN 5.274.","4.5","E"]],th:["Sem plataforma própria comparável a LegacyX ou GenWizard, vender horas de modernização é perder para ferramentas cobradas por minuto.","H"]}};
document.querySelectorAll(".ws").forEach(h=>{const w=WS[h.dataset.pillar];h.innerHTML=`<div class="card nv" style="padding:14px 16px"><div class="eye" style="color:var(--orange-l)">Onde o DTS ganha · white space</div>${w.it.map(([t,x,c,e],i)=>`<div class="ws-i"><span class="n">${i+1}</span><div><b>${t}</b> ${e==="E"?'<span class="ev">E</span>':'<span class="hy">H</span>'}<p>${x}</p>${plink(c,"sm dk")}</div></div>`).join("")}</div>
  <div class="card" style="margin-top:10px;border:1.5px dashed var(--orange);background:var(--orange-bg);padding:10px 14px"><div class="eye" style="color:var(--orange-dd);margin-bottom:4px">Ameaça a monitorar ${w.th[1]==="E"?'<span class="ev">E</span>':'<span class="hy">H</span>'}</div><p style="font:600 12.5px/1.45 var(--fb);color:#5A3A0A">${w.th[0]}</p></div>`});

/* ---------- casos M&A e linha regulatória ---------- */
[["MBRF","Marfrig + BRF, concluída em set/2025; sinergias anunciadas de R$ 485 mi/ano","Integração"],["Petz + Cobasi","Cade aprovou em dez/2025, com venda de 26 lojas","Integração"],["Braskem","Controle passa à IG4 (abr/2026)","Troca de controle"],["Raízen","Separação em Energia e Combustíveis até o fim de 2027","Carve-out"],["Motiva","Venda de participações em aeroportos por R$ 5,2 bi","Desinvestimento"]].forEach(([n,x,t])=>{const d=H("div",{class:"kpi-t",style:"padding:10px 12px"},$("p3cases"));d.innerHTML=`<span class="st ${t==="Carve-out"?"new":t==="Integração"?"ai":"keep"}" style="font-size:8.5px">${t}</span><div style="font:700 19px/1.1 var(--fh);color:var(--navy);margin-top:6px">${n}</div><div class="l" style="font-size:11.3px">${x}</div>`});
(function(){const st=[["2026","Alíquota-teste de 1% (CBS 0,9% + IBS 0,1%)"],["01/01/2027","CBS plena; PIS/Cofins extintos"],["2027","Fim da manutenção padrão do SAP ECC (extensível a 2030)"],["2029–32","ICMS/ISS caem 10 p.p. ao ano"],["2033","ICMS e ISS extintos"]];const h=$("p2time");h.innerHTML=`<div class="rt">${st.map(([d,t],i)=>`<div class="rt-i${i===1?" hot":""}"><i></i><b>${d}</b><span>${t}</span></div>`).join("")}</div>`})();

/* ---------- before / after por pilar ---------- */
const BAS={};
document.querySelectorAll(".bap").forEach(host=>{const n=+host.dataset.pillar,pl=PILLARS[n-1],ps=PRODUCTS.filter(p=>p.pillar===n);
  const rows=ps.map(p=>({p,olds:OLD.filter(o=>o.to===p.code)}));const out=OLD.filter(o=>o.p===n&&!ps.some(p=>p.code===o.to));const R=rows.length+out.length;
  const DN={keep:"Manter",ai:"Remodelar",merge:"Fundir",cut:"Retirar"};
  const asisRow=r=>{if(!r.olds.length)return`<div class="c a"><div class="asis-none">— não existe hoje —</div></div><div class="c b"><div class="why"><b>Lacuna:</b> ${strip(r.p.pain[0])}.</div></div>`;
    const prim=r.olds.find(o=>o.d!=="merge"&&o.d!=="cut")||r.olds[0];
    return`<div class="c a">${r.olds.map(o=>`<span class="asis-chip ${o.d}">${o.n}${o.p!==n?` <i>(Pilar ${o.p})</i>`:""}</span>`).join("")}</div><div class="c b"><div class="why">${r.olds.length>1?`<b>Sobreposição:</b> ${r.olds.length} serviços para o mesmo comprador. `:""}${prim.w}</div><span class="dec">${[...new Set(r.olds.map(o=>DN[o.d]))].join(" + ")}</span></div>`};
  const tobeRow=r=>{const p=r.p;return`<div class="c a"><div class="tb-code">${p.code}</div>${stTag(p.st)}${p.sig?'<span class="sig2">★ Signature</span>':""}</div><a class="c b tb" href="#p=${p.id}" data-pd="${p.id}"><div class="tb-nm">${p.name}<span class="more">ficha ›</span></div><div class="tb-tl">${p.tagline}</div><div class="tb-ai"><b>IA:</b> ${strip(p.ai[0])}</div></a>`};
  const outAsis=o=>`<div class="c a"><span class="asis-chip ${o.d}">${o.n}</span></div><div class="c b"><div class="why">${o.w}</div><span class="dec">${o.d==="cut"?"Retirar":"Transferir"}</span></div>`;
  const outTobe=o=>{const d=PBY(o.to);return`<div class="c a"><span class="st ${o.d==="cut"?"cut":"merge"}">${o.d==="cut"?"Retirado":"Transferido"}</span></div><a class="c b tb" href="#p=${d.id}" data-pd="${d.id}"><div class="tb-nm" style="font-size:13px;color:#55697C">→ ${o.d==="cut"?"Absorvido por":"Agora no Pilar "+d.pillar+":"} ${d.code} ${d.name}</div><div class="tb-tl">${o.n} ${o.d==="cut"?"deixa de ser vendido isolado.":"muda de pilar."}</div></a>`};
  const head=(a,b)=>`<div class="c hd a">${a}</div><div class="c hd b">${b}</div>`;
  const grid=`grid-template-rows:26px repeat(${R},1fr)`;
  host.innerHTML=`<div style="display:grid;grid-template-columns:1fr 360px;gap:16px;height:100%">
   <div class="ba" style="height:100%">
     <div class="ba-layer ba-tobe"><div class="ba-grid" style="${grid}">${head("Status","Produto proposto · papel da IA")}${rows.map(tobeRow).join("")}${out.map(outTobe).join("")}</div></div>
     <div class="ba-layer ba-asis"><div class="ba-grid" style="${grid}">${head("Serviço atual","Diagnóstico · por que mudar")}${rows.map(asisRow).join("")}${out.map(outAsis).join("")}</div></div>
   </div>
   <div class="ba-side">
     <div class="seg ba-seg"><button data-v="100">Hoje</button><button data-v="38.5" class="on">Lado a lado</button><button data-v="0">Proposta</button></div>
     <div class="card nv" style="margin-top:12px;padding:12px 16px"><div class="eye" style="color:var(--orange-l)">Pilar ${n} · ${pl.name}</div><div class="big" style="color:#fff;font-size:52px">${pl.was} → ${pl.now}</div><p>serviços → produtos</p></div>
     <div class="card" style="margin-top:10px;padding:12px 16px">${["keep","ai","new"].map(k=>{const c=ps.filter(p=>p.st===k).length;return`<div class="bar-r"><span>${STATUS[k][0]}</span><i><b class="${k}" style="width:${c/ps.length*100}%"></b></i><em>${c}</em></div>`}).join("")}</div>
     <div class="card soft" style="margin-top:10px;padding:10px 14px"><h4>O que muda</h4><ul>${pillarNotes(n).map(x=>`<li>${x}</li>`).join("")}</ul></div>
     ${ps.filter(p=>p.st==="new").map(p=>`<a href="#p=${p.id}" data-pd="${p.id}" class="card holo" style="display:block;margin-top:10px;padding:10px 14px;background:linear-gradient(110deg,#FFF6EC,#fff 60%);border-color:#F8C58C"><div class="eye" style="color:var(--orange-dd);margin-bottom:2px">★ Novo com IA · ${p.code}</div><h4 style="font-size:14px">${p.name}</h4><p style="font-size:11.5px">${p.kpis[0][0]} ${strip(p.kpis[0][1])}</p></a>`).join("")}
     <div class="hint" style="margin-top:10px">arraste o divisor · clique no produto</div>
   </div></div>`;
  let lastOn="";const ba=BeforeAfter(host.querySelector(".ba"),{rest:38.5,onMove:x=>{let k="";host.querySelectorAll(".ba-seg button").forEach(b=>{const on=Math.abs(+b.dataset.v-x)<3;b.classList.toggle("on",on);if(on)k=b.dataset.v});if(k!==lastOn){lastOn=k;segSync(host.querySelector(".ba-seg"))}}});BAS[n]=ba;
  const sg=host.querySelector(".ba-seg");sg.querySelectorAll("button").forEach(b=>b.onclick=()=>{ba.tween(+b.dataset.v,800);sg.querySelectorAll("button").forEach(x=>x.classList.toggle("on",x===b));segSync(sg)});
  ENTER[host.closest(".slide").dataset.t]=()=>{segSync(sg);ba.demo();setTimeout(()=>segSync(sg),2700)}});
PRINT.push(()=>Object.values(BAS).forEach(b=>b.set(38.5)));
function pillarNotes(n){return{1:["3 ofertas de liderança viram 1 (Interim & Embedded)","Tax + incentivos viram 1 produto com A&M Tax","Resiliência migra para o Pilar 4","Novo: AI Value & Governance Office"],
 2:["TMO + Modelo de Implantação viram o Predictive Transformation Office","ERP Readiness incorpora a Reforma Tributária","IT Business Partner sai (vai para 1.3)","Novo: AI-Native IT Productivity"],
 3:["8 fases viram 4 produtos + 1 assinatura","DD buy + sell = 1 produto, 3 níveis","IMO + SMO = 1 escritório","Playbook vira motor do PE Tech Value Radar"],
 4:["Nomes pelo que entregam (‘Strategy Application’ → Portfolio Rationalization)","Infra deixa de soar como serviço gerenciado","Resiliência chega do Pilar 1","Novo: Legacy X-Ray & AI Modernization"]}[n]}

/* ---------- fábrica: card stack + anatomia ---------- */
(function(){const C=[["01","Codificar o método","Etapas, entregáveis, templates e critérios de qualidade iguais em todo cliente.",["Ficha padrão (8 blocos)","Kit: data request, roteiros, modelos","Definição de ‘pronto’ por etapa"]],
  ["02","Embarcar a IA","Agentes e prompts testados por etapa, rodando em LLM corporativo seguro.",["Biblioteca de agentes por produto","Revisão humana obrigatória (sênior assina)","Trilha de evidências: cada achado cita a fonte"]],
  ["03","Capturar dados","Cada projeto alimenta o benchmark DTS, anonimizado: a vantagem cresce a cada venda.",["Taxonomia única (TBM, maturidade, preços)","Benchmark DTS Brasil","Base para radares por assinatura"]],
  ["04","Precificar","Preço por valor, não por hora: sprint fixo, execução com êxito, assinatura.",["Faixas por porte de cliente","Success fee onde há economia mensurável","Assinatura para radares e escritórios"]],
  ["05","Equipar o time","Dono de produto, squad padrão e trilha de skills com certificação interna.",["1 dono por pilar + 1 de IA","Squad: sócio, gerente, consultores, eng. de IA/dados","Certificação interna por produto"]],
  ["06","Escalar e medir","Funil, conversão, margem e NPS por produto; revisão trimestral do portfólio.",["Comitê trimestral: escalar · ajustar · aposentar","Conversão sprint → execução","Casos de sucesso viram material de venda"]]];
  const EXS=["Ex.: <b>3.1 Tech DD</b> · checklist padrão, modelo de custos e relatório em 3 níveis", "Ex.: <b>1.5 Spend</b> · agente lê contratos e faturas; o gerente valida cada achado", "Ex.: <b>3.5 PE Tech Value Radar</b> · score comparável entre investidas", "Ex.: <b>1.7 AI Office</b> · assinatura Essencial · Avançado · Regulado", "Ex.: <b>2.4 Project Rescue</b> · squad forense pronto em 1 semana", "Ex.: <b>1.1 Diagnostic → 1.4/1.5</b> · meta de conversão sprint → execução"];
  const cs=CardStack($("csScene"),C.map(([n,t,p,li],i)=>`<div class="q">${n}</div><div class="k">PASSO ${n} DE 06</div><h3>${t}</h3><p>${p}</p><ul>${li.map(x=>`<li>${x}</li>`).join("")}</ul><div class="ex">${EXS[i]}</div>`),$("csDots"));
  $("csNext").onclick=()=>cs.next();$("csPrev").onclick=()=>cs.prev();ENTER["Fábrica de produtos"]=()=>cs.reset();
  [["1","Público-alvo"],["2","Problema resolvido"],["3","Entregáveis"],["4","Método e etapas"],["S","Skills aplicadas"],["5","Ferramentas e dados"],["6","Papel da IA"],["7","Produtização"]].forEach(([n,t],i)=>{const d=H("div",{class:"anat-i","data-a":"up",style:`--d:${3+i}`},$("anat"));d.innerHTML=`<i>${n}</i><span>${t}</span>`});
  [["Sprint","Diagnóstico com escopo e preço fixos (2–4 semanas)",["1.1","2.4","3.1","4.6"]],["Execução","Programa com fee + êxito ou marcos",["1.5","2.3","3.3","4.3"]],["Assinatura","Radar ou escritório contínuo: receita recorrente",["1.7","3.5","1.5"]]].forEach(([t,x,ps],i)=>{const d=H("div",{class:"card","data-a":"up",style:`--d:${8+i};padding:10px 12px;border-top:4px solid ${["#5E8AB4","#33556D","#F78C16"][i]}`},$("tiers"));d.innerHTML=`<h4>${i+1} · ${t}</h4><p style="font-size:11.8px">${x}</p><div style="margin-top:6px;display:flex;flex-wrap:wrap;gap:4px">${ps.map(c=>`<a href="#p=${PBY(c).id}" data-pd="${PBY(c).id}" class="plink sm ${PBY(c).st}">${c}</a>`).join("")}</div>`});
  [["Demanda recorrente","≥ 3 clientes por ano com o mesmo problema"],["Método repetível","≥ 70% do escopo igual entre clientes"],["Dados reaproveitáveis","cada projeto melhora o benchmark e o próximo"],["IA com ganho real","≥ 30% menos esforço nas etapas automatizadas"],["Preço por valor","fixo, êxito ou assinatura, defensável pelo resultado"],["Dono e squad","responsável pelo P&L e time treinado"]].forEach(([t,x],i)=>{const d=H("div",{class:"gate-i","data-a":"up",style:`--d:${14+i}`},$("gate"));d.innerHTML=`<i>✓</i><div><b>${t}</b><p>${x}</p></div>`});
  [["Dono de produto","1 por pilar + 1 de IA: P&L, roadmap e qualidade da ficha"],["Squad padrão","Sócio · gerente · 2 consultores · engenheiro de IA/dados"],["Comitê trimestral","Escalar · ajustar · aposentar com base em receita, margem e conversão"]].forEach(([t,x],i)=>{const d=H("div",{class:"card soft","data-a":"up",style:`--d:${11+i};padding:10px 12px`},$("opm"));d.innerHTML=`<h4>${t}</h4><p style="font-size:11.8px">${x}</p>`})})();

/* ---------- roadmap + decisões ---------- */
(function(){let tl=null;ENTER["Roadmap e decisões"]=()=>{if(!tl)tl=Timeline($("tlLaunch"),TL_LAUNCH,{w:1508,y:196,cardY:14,x0:110,x1:1400,dwell:2400});tl.play()};$("tl2Play").onclick=()=>tl&&tl.play();PRINT.push(()=>{if(!tl)tl=Timeline($("tlLaunch"),TL_LAUNCH,{w:1508,y:196,cardY:14,x0:110,x1:1400,dwell:2400});tl.stopAuto();tl.set(1)});
  ["<b>Aprovar o portfólio de 24 produtos</b> (5 manter · 15 aprimorar · 4 criar) e os 4 A&amp;M Signature.","<b>Nomear donos de produto</b> (1 por pilar + 1 de IA) e instituir o comitê trimestral de portfólio.","<b>Investir na plataforma DTS</b>: LLM corporativo seguro, Spend Radar, benchmark DTS Brasil, biblioteca de agentes.","<b>Atacar as janelas de 2027</b>: Reforma Tributária (CBS em 01/01/2027) e orçamento/custo de tecnologia.","<b>Validar os 4 produtos novos</b> com 3–5 clientes-piloto cada, incluindo 1–2 fundos de PE.","<b>Alinhar fronteiras</b> com A&amp;M Tax, Data &amp; IA, PEPI e o Global AI Board (reuso de A&amp;M Assist e DiligenceGPT)."].forEach(x=>H("li",{html:x},$("decisions")));
  [["Pessoas","4 donos de produto (1 por pilar) + 1 de IA; 2–3 engenheiros de IA/dados; trilha de skills para o time"],["Ferramentas","LLM corporativo seguro; Power BI/Fabric; análise de código para DD e legado; repositório de agentes e prompts"],["Parcerias","1 hyperscaler e 1 laboratório de IA; ferramentas de code analysis e FinOps; A&M Tax e PEPI internamente"],["Dados","Benchmark DTS Brasil (gasto, maturidade, preços unitários), alimentado por cada projeto, anonimizado"]].forEach(([t,x],i)=>{const d=H("div",{class:"cap-i","data-a":"up",style:`--d:${10+i}`},$("caps"));d.innerHTML=`<b>${t}</b><p>${x}</p>`});
  [["≥30%","da receita DTS de produtos com IA no método em 2027"],["≥10%","de receita recorrente (radares e escritórios)"],["−30%","no tempo de entrega de diagnósticos e DDs"],["≥40%","de conversão sprint → execução"]].forEach(([v,l])=>{const d=H("div",null,$("kpisOK"));d.innerHTML=`<div style="font:700 28px/1 var(--fh);color:var(--orange-l)">${v}</div><div style="font:500 11.5px/1.35 var(--fb);color:#C8DBEB;margin-top:3px">${l}</div>`})})();

/* ---------- fontes e método ---------- */
(function(){[["1","Big Four","Deloitte, PwC, EY e KPMG: nomes de ofertas, IA e sinais no Brasil · 62 fontes"],["2","Estratégia, integradores, pares e A&M","McKinsey, BCG, Bain, Kearney, Accenture, IBM, Capgemini, NTT DATA, hyperscalers, AlixPartners, A&M"],["3","Mercado Brasil e regulação","ABES/IDC, Cetic.br, IBGE, KPMG M&A, Reforma Tributária, Lei do Bem, PL 2338, ANPD, BACEN"],["4","Ferramentas de IA e produtização","Gartner, MIT NANDA, HFS, Everest, Forrester e fornecedores (AWS, IBM, GitHub, CAST, Vertice, Flexera)"],["H","Avaliação do portfólio","Escores do Raio-X e desenho dos produtos: julgamento qualitativo DTS, a calibrar com os sócios"]].forEach(([n,t,x])=>{const d=H("div",{class:"mt-i"},$("method"));d.innerHTML=`<i class="${n==="H"?"h":""}">${n}</i><div><b>${t}</b><p>${x}</p></div>`});
  const SRC=[["Mercado de TI e IA","ABES/IDC, Mercado Brasileiro de Software (mar/2026) · IDC, gastos com IA (2026) · Cetic.br, TIC Empresas 2025 · IBGE, PINTEC Semestral (set/2025) · Gartner, gastos de TI e IA (abr–mai/2026)"],
   ["Valor de IA e projetos","PwC, 29ª CEO Survey (jan/2026) · Deloitte, State of AI 2026 · MIT NANDA, GenAI Divide (2025) · Gartner, agentic AI (jun/2025) e ERP (nov/2025) · McKinsey/Oxford, grandes projetos de TI"],
   ["M&A","KPMG, Pesquisa de Fusões e Aquisições 2025 (mar/2026) e 1S26 (ago/2026) · TTR/Aon/Datasite (2026) · imprensa: MBRF, Petz+Cobasi, Braskem, Raízen, Motiva"],
   ["Regulação","EC 132/2023 · LC 214/2025 · LC 227/2026 · Decreto 12.955/2026 · LC 224/2025 · PL 2338/2023 (MobileTime, ago/2026) · Lei 15.352/2026 (ANPD) · Res. CMN 5.274/2025"],
   ["Consultorias","Press releases de Deloitte, PwC, EY e KPMG (2025–26) · McKinsey via BI/HBR (jan/2026) · BCG (abr/2026) · Bain (jul/2026) · AlixPartners (ago/2026) · A&M (05/05/2026) e Bloomberg (04/05/2026)"],
   ["Ferramentas","AWS Transform (SiliconANGLE mai/2025; preços set/2026) · IBM WCA for Z e Bob · GitHub Copilot app modernization · CAST (caso EY) · Vertice · Flexera State of the Cloud 2026 · State of FinOps 2026"]];
  SRC.forEach(([t,x],i)=>{const d=H("div",{class:"card","data-a":"up",style:`--d:${2+i};padding:10px 14px`},$("sources"));d.innerHTML=`<h4>${t}</h4><p style="font-size:11.5px;line-height:1.5">${x}</p>`});
  const g=H("div",{class:"card","data-a":"up",style:"--d:9;grid-column:1/-1;padding:10px 14px;border:1.5px dashed var(--orange);background:var(--orange-bg)"},$("sources"));g.innerHTML=`<h4 style="color:#8A4A05">Lacunas a investigar antes do uso externo <span class="hy">pendente</span></h4><ul style="padding-left:16px;margin-top:4px;columns:2;column-gap:26px">${["Posicionamento verificado de Stefanini, Sonda, NTT DATA, Compass UOL, Accenture Brasil, Bip, Visagio, Integration e ISG","Ofertas de FTI, Huron, Accordion, West Monroe e Crosslake (pares de PE) não reverificadas","Ofertas de Lei do Bem de Deloitte, PwC e EY; nomes oficiais em português das ofertas das Big Four","Status da sanção do Redata e da votação do PL 2338 após as eleições","Discrepância IDC sobre gasto com IA no Brasil (US$ 3,4 bi × US$ 4,2 bi)","Validação dos 4 produtos novos com 3–5 clientes-piloto cada"].map(x=>`<li style="font:500 11.5px/1.45 var(--fb);color:#5A3A0A;break-inside:avoid">${x}</li>`).join("")}</ul>`})();

/* ---------- jornada comercial e posicionamento por pilar ---------- */
const JR={1:[["Gatilho","Troca de CIO · orçamento 2027 · conselho cobra IA",[],"evento que abre a conversa"],["Entrada · sprint","Diagnóstico em 3 semanas",["1.1"],"valor em jogo em R$ e 10 decisões"],["Expansão · execução","Assumir, redesenhar e cortar",["1.3","1.4","1.5"],"a A&M entra no comando"],["Recorrência","Radar e escritório contínuos",["1.5","1.7"],"assinatura que sustenta o resultado"]],
 2:[["Gatilho","CBS em 01/01/2027 · go-live em risco · IA ociosa",[],"prazo fixo e risco alto"],["Entrada · sprint","Readiness ou diagnóstico forense",["2.2","2.4"],"4–8 semanas, preço fixo"],["Expansão · execução","Governar, recuperar, contratar",["2.3","2.1"],"entrega garantida"],["Recorrência","IA na própria TI, em ondas",["2.6","2.5"],"ganho medido trimestre a trimestre"]],
 3:[["Gatilho","Mandato de compra ou venda · carve-out anunciado",[],"relógio do deal"],["Entrada · sprint","Red flag em 1 semana",["3.1"],"DD com IA, 3 níveis"],["Expansão · execução","Dia 1, TSA e sinergias",["3.2","3.3","3.4"],"do signing ao Dia 100"],["Recorrência","Radar do portfólio do fundo",["3.5"],"assinatura trimestral"]],
 4:[["Gatilho","Renovação VMware · incidente · legado sem dono",[],"custo ou risco explícito"],["Entrada · sprint","Raio-X do legado ou TCO",["4.6","4.3"],"4–6 semanas, preço fixo"],["Expansão · execução","Arquitetura, racionalização, assurance",["4.1","4.2","4.4"],"rota e garantia"],["Recorrência","Resiliência e arquitetura vivas",["4.5","4.1"],"exercícios anuais e repositório"]]};
document.querySelectorAll(".jr-wrap").forEach(h=>{const n=h.dataset.pillar;h.innerHTML=`<div class="ttl" style="font-size:14px">Jornada comercial do pilar · land → expand → recorrência <span class="hy">Hipótese</span></div><div class="jr">${JR[n].map(([k,t,ps,x],i)=>`<div class="jr-i ${i===0?"l":i===3?"r":""}"><div class="k">${k}</div><b>${t}</b><div>${ps.map(c=>plink(c,"sm")).join("")}</div><p style="margin-top:3px">${x}</p></div>`).join("")}</div>`});
const POS={1:"Para <b>CEOs, CFOs, conselhos e fundos</b> que precisam de resultado de tecnologia agora, o DTS é <em>a liderança que assume o cargo e entrega valor em R$, com IA no método</em>. Diferente de Big Four e estratégia, <b>assinamos o resultado</b> e não vendemos plataforma.",
 2:"Para <b>CFOs, CIOs e sponsors</b> de programas obrigatórios e críticos, o DTS é <em>a voz independente que garante a entrega</em> (Reforma, ERP, IA). Diferente de integradores e fornecedores, <b>não vendemos software nem horas de fábrica</b>: respondemos por prazo e valor.",
 3:"Para <b>fundos de PE e compradores estratégicos</b>, o DTS é <em>o operador de tecnologia do signing à saída</em>: DD com IA em dias, Dia 1 sem susto e sinergias que viram EBITDA. Diferente de quem só diligencia, <b>executamos o que recomendamos</b>.",
 4:"Para <b>CIOs e CFOs</b> presos a legado caro e arriscado, o DTS é <em>quem escolhe a rota e garante a modernização</em>, usando IA para ler o legado, neutro em fornecedor. Diferente de hyperscalers e fábricas, <b>não revendemos ferramenta</b>: respondemos pelo business case."};
document.querySelectorAll(".pos").forEach(h=>{h.innerHTML=`<div class="t">Posicionamento proposto</div><p>${POS[h.dataset.pos]} <span class="hy">Hipótese</span></p>`});

/* hash externo (#p=...) */
addEventListener("hashchange",()=>{const h=location.hash.slice(1);if(h.startsWith("p=")&&h.slice(2)!==pdOpen)openPD(h.slice(2))});
boot();
